// @vitest-environment happy-dom
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import { createPinia } from 'pinia'
import { defineComponent, h, mergeProps } from 'vue'
import AppShell from './AppShell.vue'
import type { ProjectSummary, RendererApi, SessionSummary } from '@shared/project-session'
import { createRendererApiMock, createSessionSummaryFixture } from '@shared/test-fixtures'
import type { ProjectHierarchyNode } from '@renderer/stores/workspaces'
import { useSidebarStore } from '@renderer/stores/sidebar'

const baseProject: ProjectSummary = {
  id: 'project-1',
  name: 'Alpha',
  path: 'D:/workspace/alpha',
  createdAt: '2026-04-21T00:00:00.000Z',
  updatedAt: '2026-04-21T00:00:00.000Z'
}

const defaultTitleGenerationContext = {
  prompt: null,
  assistantSnippet: null,
  contextUpdatedAt: null,
  autoGeneratedTurnEpoch: null
}

const baseSession: SessionSummary = {
  ...createSessionSummaryFixture({
    id: 'session-1',
    projectId: 'project-1',
    type: 'shell',
    runtimeState: 'starting',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    blockingReason: null,
    failureReason: null,
    title: 'Alpha shell',
    summary: 'Preparing the terminal session.',
    titleGenerationContext: defaultTitleGenerationContext,
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: '2026-04-21T00:00:00.000Z',
    updatedAt: '2026-04-21T00:00:00.000Z',
    lastActivatedAt: '2026-04-21T00:00:00.000Z',
    archived: false
  })
}

const CommandSurfaceStub = defineComponent({
  name: 'CommandSurface',
  inheritAttrs: false,
  props: {
    hierarchy: { type: Array, required: true },
    activeProject: { default: null },
    activeSession: { default: null },
    activeProjectId: { default: null },
    activeSessionId: { default: null },
    visible: { type: Boolean, default: true }
  },
  emits: [
    'selectProject',
    'selectSession',
    'createProject',
    'createSession',
    'deleteProject',
    'archiveSession',
    'restoreSession',
    'restartSession',
    'openWorkspace'
  ],
  setup(props, { attrs }) {
    return () =>
      h(
        'section',
        mergeProps(attrs, {
          'data-surface': 'command',
          'data-command-surface': 'true',
          'data-testid': 'command-panel'
        }),
        props.activeSession
          ? [h('div', { 'data-testid': 'terminal-xterm' })]
          : [h('div', { class: 'terminal-empty-state' }, 'No session selected')]
      )
  }
})

const SettingsSurfaceStub = defineComponent({
  name: 'SettingsSurface',
  inheritAttrs: false,
  setup(_props, { attrs }) {
    return () =>
      h(
        'section',
        mergeProps(attrs, {
          'data-surface': 'settings',
          'aria-label': 'Settings surface'
        }),
        [h('h2', 'Settings')]
      )
  }
})

const TabBarStub = defineComponent({
  name: 'TabBar',
  props: {
    activeTab: { type: String, required: true }
  },
  emits: ['select'],
  setup(props, { emit }) {
    return () =>
      h(
        'div',
        { 'data-testid': 'sidebar-tabs', 'data-active-tab': props.activeTab },
        'Tab Bar'
      )
  }
})

const FileExplorerStub = defineComponent({
  name: 'FileExplorer',
  setup() {
    return () => h('div', { 'data-testid': 'file-explorer' }, 'File Explorer')
  }
})

const SearchPanelStub = defineComponent({
  name: 'SearchPanel',
  setup() {
    return () => h('div', { 'data-testid': 'search-panel' }, 'Search Panel')
  }
})

const SourceControlPanelStub = defineComponent({
  name: 'SourceControlPanel',
  setup() {
    return () => h('div', { 'data-testid': 'source-control-panel' }, 'Source Control')
  }
})

function mountAppShell(props: {
  hierarchy: ProjectHierarchyNode[]
  activeProjectId: string | null
  activeSessionId: string | null
  activeProject: ProjectSummary | null
  activeSession: SessionSummary | null
}) {
  return mount(AppShell, {
    global: {
      plugins: [createPinia()],
      stubs: {
        CommandSurface: CommandSurfaceStub,
        SettingsSurface: SettingsSurfaceStub,
        TabBar: TabBarStub,
        FileExplorer: FileExplorerStub,
        SearchPanel: SearchPanelStub,
        SourceControlPanel: SourceControlPanelStub
      }
    },
    props
  })
}

describe('AppShell', () => {
  beforeEach(() => {
    const stoaMock: RendererApi = createRendererApiMock({
      createProject: vi.fn().mockResolvedValue(baseProject),
      createSession: vi.fn().mockResolvedValue(baseSession),
      regenerateSessionTitle: vi.fn().mockResolvedValue(baseSession),
      getAppObservability: vi.fn().mockResolvedValue({
        blockedProjectCount: 0,
        failedProjectCount: 0,
        totalUnreadTurns: 0,
        projectsNeedingAttention: [],
        providerHealthSummary: {},
        lastGlobalEventAt: null,
        sourceSequence: 0,
        updatedAt: '2026-04-21T00:00:00.000Z'
      }),
      getUpdateState: vi.fn().mockResolvedValue({
        phase: 'idle',
        currentVersion: '0.1.0',
        availableVersion: null,
        downloadedVersion: null,
        downloadProgressPercent: null,
        lastCheckedAt: null,
        message: null,
        requiresSessionWarning: false
      }),
      checkForUpdates: vi.fn().mockResolvedValue({
        phase: 'up-to-date',
        currentVersion: '0.1.0',
        availableVersion: null,
        downloadedVersion: null,
        downloadProgressPercent: null,
        lastCheckedAt: null,
        message: 'You are up to date.',
        requiresSessionWarning: false
      }),
      downloadUpdate: vi.fn().mockResolvedValue({
        phase: 'downloaded',
        currentVersion: '0.1.0',
        availableVersion: '0.2.0',
        downloadedVersion: '0.2.0',
        downloadProgressPercent: 100,
        lastCheckedAt: null,
        message: 'Update 0.2.0 is ready to install.',
        requiresSessionWarning: false
      }),
      gitStatus: vi.fn().mockResolvedValue({
        branch: 'main',
        entries: [],
        ahead: 0,
        behind: 0
      }),
      gitBranches: vi.fn().mockResolvedValue({
        current: 'main',
        locals: ['main', 'develop'],
        remotes: []
      }),
      gitLog: vi.fn().mockResolvedValue([]),
      gitStage: vi.fn().mockResolvedValue(undefined),
      gitUnstage: vi.fn().mockResolvedValue(undefined),
      gitDiscard: vi.fn().mockResolvedValue(undefined),
      gitPush: vi.fn().mockResolvedValue(undefined),
      gitPull: vi.fn().mockResolvedValue(undefined),
      gitFetch: vi.fn().mockResolvedValue(undefined),
      gitCheckout: vi.fn().mockResolvedValue(undefined),
      gitCreateBranch: vi.fn().mockResolvedValue(undefined),
      gitRebase: vi.fn().mockResolvedValue(undefined),
      gitMerge: vi.fn().mockResolvedValue(undefined)
    })

    window.stoa = stoaMock
  })

  it('shows command/sidebar/settings activity items and defaults to command view', () => {
    const wrapper = mountAppShell({
      hierarchy: [],
      activeProjectId: null,
      activeSessionId: null,
      activeProject: null,
      activeSession: null
    })

    const labels = wrapper.findAll('[data-activity-item]').map((node) => node.attributes('data-activity-item'))
    const navigation = wrapper.get('nav[aria-label="Global activity"]')
    const commandButton = wrapper.get('button[aria-label="Command panel"]')
    const settingsButton = wrapper.get('button[aria-label="Settings"]')

    expect(labels).toEqual(['command', 'archive', 'sidebar-toggle', 'settings'])
    expect(navigation).toBeTruthy()
    expect(commandButton.attributes('aria-current')).toBe('true')
    expect(settingsButton.attributes('aria-current')).toBeUndefined()
    expect(wrapper.find('[data-command-surface="true"]').exists()).toBe(true)
    expect(wrapper.find('[data-surface="command"][aria-label="Command surface"]').exists()).toBe(true)
    expect(wrapper.find('.terminal-empty-state').exists()).toBe(true)
  })

  it('keeps stable command and active-session surface hooks when a session is selected', () => {
    const wrapper = mountAppShell({
      hierarchy: [{
        ...baseProject,
        active: true,
        archivedSessions: [],
        sessions: [{
          ...baseSession,
          active: true
        }]
      }],
      activeProjectId: baseProject.id,
      activeSessionId: baseSession.id,
      activeProject: baseProject,
      activeSession: baseSession
    })

    expect(wrapper.find('[data-surface="command"]').exists()).toBe(true)
    expect(wrapper.find('[data-command-surface="true"]').exists()).toBe(true)
    expect(wrapper.find('.terminal-empty-state').exists()).toBe(false)
    expect(wrapper.find('[data-testid="terminal-xterm"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="terminal-status-bar"]').exists()).toBe(false)
  })

  it('keeps command surface mounted and hidden when the settings activity is selected', async () => {
    const wrapper = mountAppShell({
      hierarchy: [],
      activeProjectId: null,
      activeSessionId: null,
      activeProject: null,
      activeSession: null
    })

    const commandSurface = wrapper.get('[data-surface="command"][aria-label="Command surface"]')

    await wrapper.get('button[aria-label="Settings"]').trigger('click')

    expect(wrapper.get('[data-surface="settings"][aria-label="Settings surface"]')).toBeTruthy()
    expect(wrapper.get('button[aria-label="Settings"]').attributes('aria-current')).toBe('true')
    expect(wrapper.get('[data-surface="command"][aria-label="Command surface"]').element).toBe(commandSurface.element)
    expect(wrapper.get('[data-surface="command"][aria-label="Command surface"]').attributes('style')).toContain('display: none;')
    expect(wrapper.find('[data-surface="command"][aria-label="Command surface"]').exists()).toBe(true)
    expect(wrapper.findComponent({ name: 'CommandSurface' }).props('visible')).toBe(false)
  })

  it('keeps activity icons rendered while switching surfaces', async () => {
    const wrapper = mountAppShell({
      hierarchy: [],
      activeProjectId: null,
      activeSessionId: null,
      activeProject: null,
      activeSession: null
    })

    const expectStableIcons = () => {
      const items = wrapper.findAll('[data-activity-item]')
      const icons = wrapper.findAll('[data-activity-icon]')

      expect(items).toHaveLength(4)
      expect(icons).toHaveLength(4)
      expect(wrapper.get('[data-activity-item="command"]').find('[data-activity-icon]').exists()).toBe(true)
      expect(wrapper.get('[data-activity-item="archive"]').find('[data-activity-icon]').exists()).toBe(true)
      expect(wrapper.get('[data-activity-item="sidebar-toggle"]').find('[data-activity-icon]').exists()).toBe(true)
      expect(wrapper.get('[data-activity-item="settings"]').find('[data-activity-icon]').exists()).toBe(true)
    }

    expectStableIcons()

    await wrapper.get('button[aria-label="Settings"]').trigger('click')
    expectStableIcons()

    await wrapper.get('button[aria-label="Command panel"]').trigger('click')
    expectStableIcons()
  })

  it('forwards restoreSession from command surface', async () => {
    const wrapper = mountAppShell({
      hierarchy: [{
        ...baseProject,
        active: false,
        sessions: [],
        archivedSessions: [{
          ...baseSession,
          id: 'session-archived',
          archived: true,
          active: false
        }]
      }],
      activeProjectId: null,
      activeSessionId: null,
      activeProject: null,
      activeSession: null
    })

    await wrapper.findComponent({ name: 'CommandSurface' }).vm.$emit('restoreSession', 'session-archived')

    expect(wrapper.emitted('restoreSession')).toEqual([['session-archived']])
  })

  it('forwards restartSession from command surface', async () => {
    const wrapper = mountAppShell({
      hierarchy: [{
        ...baseProject,
        active: true,
        archivedSessions: [],
        sessions: [{
          ...baseSession,
          active: true
        }]
      }],
      activeProjectId: baseProject.id,
      activeSessionId: baseSession.id,
      activeProject: baseProject,
      activeSession: baseSession
    })

    await wrapper.findComponent({ name: 'CommandSurface' }).vm.$emit('restartSession', 'session-1')

    expect(wrapper.emitted('restartSession')).toEqual([['session-1']])
  })

  it('forwards openWorkspace from command surface', async () => {
    const wrapper = mountAppShell({
      hierarchy: [{
        ...baseProject,
        active: true,
        archivedSessions: [],
        sessions: [{
          ...baseSession,
          active: true
        }]
      }],
      activeProjectId: baseProject.id,
      activeSessionId: baseSession.id,
      activeProject: baseProject,
      activeSession: baseSession
    })

    await wrapper.findComponent({ name: 'CommandSurface' }).vm.$emit('openWorkspace', {
      sessionId: 'session-1',
      target: 'ide'
    })

    expect(wrapper.emitted('openWorkspace')).toEqual([
      [{ sessionId: 'session-1', target: 'ide' }]
    ])
  })

  describe('Sidebar integration', () => {
    it('sidebar is mounted on command surface but closed by default', () => {
      const wrapper = mountAppShell({
        hierarchy: [],
        activeProjectId: null,
        activeSessionId: null,
        activeProject: null,
        activeSession: null
      })

      const sidebar = wrapper.get('[data-testid="right-sidebar"]')
      expect(sidebar.classes()).toContain('right-sidebar-closed')
    })

    it('sidebar is not rendered on non-command surfaces', async () => {
      const wrapper = mountAppShell({
        hierarchy: [],
        activeProjectId: null,
        activeSessionId: null,
        activeProject: null,
        activeSession: null
      })

      // Sidebar exists on command surface
      expect(wrapper.find('[data-testid="right-sidebar"]').exists()).toBe(true)

      // Navigate to settings
      await wrapper.get('button[aria-label="Settings"]').trigger('click')

      // Sidebar DOM is gone entirely
      expect(wrapper.find('[data-testid="right-sidebar"]').exists()).toBe(false)
    })

    it('sidebar re-mounts with open state when returning to command surface', async () => {
      const pinia = createPinia()
      const wrapper = mount(AppShell, {
        global: {
          plugins: [pinia],
          stubs: {
            CommandSurface: CommandSurfaceStub,
            SettingsSurface: SettingsSurfaceStub,
            TabBar: TabBarStub,
            FileExplorer: FileExplorerStub,
            SearchPanel: SearchPanelStub,
            SourceControlPanel: SourceControlPanelStub
          }
        },
        props: {
          hierarchy: [],
          activeProjectId: null,
          activeSessionId: null,
          activeProject: null,
          activeSession: null
        }
      })

      // Open sidebar via store
      const sidebarStore = useSidebarStore(pinia)
      sidebarStore.setOpen(true)
      await wrapper.vm.$nextTick()
      expect(wrapper.get('[data-testid="right-sidebar"]').classes()).not.toContain('right-sidebar-closed')

      // Navigate away — sidebar unmounts
      await wrapper.get('button[aria-label="Settings"]').trigger('click')
      expect(wrapper.find('[data-testid="right-sidebar"]').exists()).toBe(false)

      // Navigate back — sidebar re-mounts with open state from store
      await wrapper.get('button[aria-label="Command panel"]').trigger('click')
      expect(wrapper.get('[data-testid="right-sidebar"]').classes()).not.toContain('right-sidebar-closed')
    })

    it('sidebar stays closed when returning if it was never opened', async () => {
      const wrapper = mountAppShell({
        hierarchy: [],
        activeProjectId: null,
        activeSessionId: null,
        activeProject: null,
        activeSession: null
      })

      // Sidebar is closed by default
      expect(wrapper.get('[data-testid="right-sidebar"]').classes()).toContain('right-sidebar-closed')

      // Navigate away and back
      await wrapper.get('button[aria-label="Settings"]').trigger('click')
      await wrapper.get('button[aria-label="Command panel"]').trigger('click')

      // Should still be closed
      expect(wrapper.get('[data-testid="right-sidebar"]').classes()).toContain('right-sidebar-closed')
    })
  })
})
