import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { mount } from '@vue/test-utils'
import { describe, expect, test, vi, beforeEach, afterEach } from 'vitest'
import { nextTick } from 'vue'
import { createPinia, setActivePinia } from 'pinia'
import type { ProjectSummary, SessionSummary } from '@shared/project-session'
import type { SessionPresenceSnapshot } from '@shared/observability'
import { useSettingsStore } from '@renderer/stores/settings'
import { toActiveSessionViewModel } from '@renderer/stores/observability-view-models'

const terminalViewportPath = resolve(dirname(fileURLToPath(import.meta.url)), 'TerminalViewport.vue')

vi.mock('@xterm/xterm', () => {
  class Terminal {
    static instances: Terminal[] = []
    static failOpen = false
    options: Record<string, unknown>
    cols = 80
    rows = 24
    writes: string[] = []
    unicode = { activeVersion: '6' }
    dataHandlers: Array<(data: string) => void> = []
    binaryHandlers: Array<(data: string) => void> = []

    constructor(options: Record<string, unknown> = {}) {
      this.options = options
      Terminal.instances.push(this)
    }

    open() {
      if (Terminal.failOpen) {
        throw new Error('xterm open failed')
      }
    }
    attachCustomKeyEventHandler() {}
    getSelection() {
      return ''
    }
    focus() {}
    write(data: string, callback?: () => void) {
      this.writes.push(data)
      callback?.()
    }
    onData(cb: (data: string) => void) {
      this.dataHandlers.push(cb)
      return { dispose: () => {} }
    }
    onBinary(cb: (data: string) => void) {
      this.binaryHandlers.push(cb)
      return { dispose: () => {} }
    }
    loadAddon() {}
    dispose() {}
  }
  return { Terminal }
})

vi.mock('@xterm/addon-fit', () => {
  return {
    FitAddon: class {
      fit() {}
      dispose() {}
    },
  }
})

vi.mock('@xterm/addon-unicode11', () => {
  return {
    Unicode11Addon: class {},
  }
})

vi.mock('@xterm/addon-web-links', () => {
  return {
    WebLinksAddon: class {
      constructor(
        _handler: (event: MouseEvent, uri: string) => void
      ) {}
    },
  }
})

vi.mock('@xterm/addon-webgl', () => {
  return {
    WebglAddon: class {
      onContextLoss(_handler: () => void) {}
      dispose() {}
    },
  }
})

vi.mock('@xterm/addon-clipboard', () => {
  return {
    ClipboardAddon: class {},
  }
})

vi.mock('@xterm/addon-search', () => {
  return {
    SearchAddon: class {},
  }
})

vi.mock('@xterm/addon-serialize', () => {
  return {
    SerializeAddon: class {},
  }
})

vi.mock('@renderer/terminal/shell-integration-addon', () => {
  return {
    ShellIntegrationAddon: class {
      onCommandStart?: (event: unknown) => void
      onCommandExecuted?: () => void
      onCommandFinished?: (event: unknown) => void
      onCwdChanged?: (cwd: string) => void
    },
  }
})

vi.mock('@xterm/xterm/css/xterm.css', () => ({}))

function createMockApi() {
  const callbacks = {
    terminalData: [] as Array<(chunk: { sessionId: string; data: string }) => void>,
    sessionPresence: [] as Array<(snapshot: SessionPresenceSnapshot) => void>,
  }

  return {
    windowsBuildNumber: undefined,
    getTerminalReplay: vi.fn().mockResolvedValue(''),
    sendSessionInput: vi.fn(),
    sendSessionBinaryInput: vi.fn(),
    sendSessionResize: vi.fn(),
    onTerminalData: vi.fn((cb: (chunk: { sessionId: string; data: string }) => void) => {
      callbacks.terminalData.push(cb)
      return () => {
        const idx = callbacks.terminalData.indexOf(cb)
        if (idx >= 0) callbacks.terminalData.splice(idx, 1)
      }
    }),
    onSessionPresenceChanged: vi.fn((cb: (snapshot: SessionPresenceSnapshot) => void) => {
      callbacks.sessionPresence.push(cb)
      return () => {
        const idx = callbacks.sessionPresence.indexOf(cb)
        if (idx >= 0) callbacks.sessionPresence.splice(idx, 1)
      }
    }),
    callbacks,
  }
}

const baseProject: ProjectSummary = {
  id: 'project_alpha',
  name: 'alpha',
  path: 'D:/alpha',
  createdAt: 'a',
  updatedAt: 'a',
}

const baseSession: SessionSummary = {
  id: 'session_op_1',
  projectId: 'project_alpha',
  type: 'opencode',
  runtimeState: 'alive',
  turnState: 'idle',
  turnEpoch: 0,
  lastTurnOutcome: 'none',
  hasUnseenCompletion: false,
  runtimeExitCode: null,
  runtimeExitReason: null,
  lastStateSequence: 1,
  blockingReason: null,
  failureReason: null,
  title: 'Deploy',
  summary: 'ready',
  titleGenerationContext: {
    prompt: null,
    assistantSnippet: null,
    contextUpdatedAt: null,
    autoGeneratedTurnEpoch: null
  },
  recoveryMode: 'resume-external',
  externalSessionId: 'ext-123',
  createdAt: 'a',
  updatedAt: 'a',
  lastActivatedAt: 'a',
  archived: false
}

function sessionSummary(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    ...baseSession,
    ...overrides,
  }
}

const rafQueue: Array<() => void> = []

function installRafMock() {
  window.requestAnimationFrame = (cb: FrameRequestCallback) => {
    rafQueue.push(() => cb(0))
    return 1
  }
  window.cancelAnimationFrame = (_id: number) => {
    rafQueue.length = 0
  }
}

async function flushTerminal(): Promise<void> {
  await nextTick()
  await Promise.resolve()
  const pending = rafQueue.splice(0)
  for (const cb of pending) {
    cb()
  }
  await nextTick()
  await Promise.resolve()
  await nextTick()
}

describe('TerminalViewport', () => {
  let mockApi: ReturnType<typeof createMockApi>
  let pinia: ReturnType<typeof createPinia>
  let originalRaf: typeof window.requestAnimationFrame
  let originalCancelRaf: typeof window.cancelAnimationFrame

  beforeEach(async () => {
    rafQueue.length = 0
    originalRaf = window.requestAnimationFrame
    originalCancelRaf = window.cancelAnimationFrame
    installRafMock()

    pinia = createPinia()
    setActivePinia(pinia)
    mockApi = createMockApi()
    const { Terminal } = await import('@xterm/xterm')
    ;(Terminal as unknown as { instances: unknown[] }).instances.length = 0
    ;(Terminal as unknown as { failOpen: boolean }).failOpen = false
    Object.defineProperty(window, 'stoa', {
      value: mockApi,
      configurable: true,
      writable: true
    })
  })

  afterEach(() => {
    window.requestAnimationFrame = originalRaf
    window.cancelAnimationFrame = originalCancelRaf
  })

  afterEach(() => {
    Reflect.deleteProperty(window, 'stoa')
  })

  test('renders empty state when no session', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: null, session: null },
    })
    expect(wrapper.find('.terminal-empty-state').exists()).toBe(true)
  })

  test('renders the terminal when a session is present', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    expect(wrapper.find('.terminal-viewport__xterm').exists()).toBe(true)
    expect(wrapper.find('.terminal-viewport__xterm-mount').exists()).toBe(true)
  })

  test('renders workspace quick actions and forwards openWorkspace requests', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    expect(wrapper.find('[data-testid="workspace.quick-actions"]').exists()).toBe(true)

    await wrapper.get('[data-testid="workspace.open-file-manager"]').trigger('click')

    expect(wrapper.emitted('openWorkspace')).toEqual([
      [{ sessionId: 'session_op_1', target: 'file-manager' }]
    ])
  })

  test('mounts the running xterm surface inside a visual shell when session is running', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    expect(wrapper.find('.terminal-viewport__xterm').exists()).toBe(true)
    expect(wrapper.find('.terminal-viewport__shell').exists()).toBe(true)
    expect(wrapper.find('.terminal-viewport__xterm-mount').exists()).toBe(true)
    expect(wrapper.find('.terminal-viewport__xterm-shell').exists()).toBe(false)
  })

  test('running terminal structure keeps the xterm mount inside the visual shell wrapper', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    const xtermSurface = wrapper.find('.terminal-viewport__xterm')
    expect(xtermSurface.exists()).toBe(true)
    const shell = xtermSurface.find('.terminal-viewport__shell')
    expect(shell.exists()).toBe(true)
    expect(shell.find('.terminal-viewport__xterm-mount').exists()).toBe(true)
  })

  test('registers onTerminalData listener on mount', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    expect(mockApi.onTerminalData).toHaveBeenCalled()
    expect(mockApi.onSessionPresenceChanged).toHaveBeenCalled()
  })

  test('forwards xterm binary input through sendSessionBinaryInput with byte preservation', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as {
      instances: Array<{ binaryHandlers: Array<(data: string) => void> }>
    }).instances.at(-1)

    instance?.binaryHandlers[0]?.('\u001b[M')

    expect(mockApi.sendSessionBinaryInput).toHaveBeenCalledWith(
      'session_op_1',
      Uint8Array.from([0x1b, 0x5b, 0x4d])
    )
  })

  test('replays the latest terminal backlog before consuming live chunks', async () => {
    mockApi.getTerminalReplay.mockResolvedValue('restored frame')

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()
    await flushTerminal()

    expect(mockApi.getTerminalReplay).toHaveBeenCalledWith('session_op_1')

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances.at(-1)
    expect(instance?.writes).toContain('restored frame')

    mockApi.callbacks.terminalData.forEach((cb) => {
      cb({ sessionId: 'session_op_1', data: 'live chunk' })
    })
    await flushTerminal()

    expect(instance?.writes).toContain('live chunk')
  })

  test('replay/live merge never drops repeated output bytes', async () => {
    let resolveReplay!: (value: string) => void
    mockApi.getTerminalReplay = vi.fn().mockImplementation(() => {
      return new Promise<string>((resolve) => {
        resolveReplay = resolve
      })
    })

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    mockApi.callbacks.terminalData.forEach((cb) => {
      cb({ sessionId: 'session_op_1', data: 'AB' })
    })

    resolveReplay('ABAB')
    await flushTerminal()
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances.at(-1)
    expect(instance?.writes).toEqual(['ABAB', 'AB'])
  })

  test('exit event buffered before replay resolves is rendered after replay and buffered live output', async () => {
    let resolveReplay!: (value: string) => void
    mockApi.getTerminalReplay = vi.fn().mockImplementation(() => {
      return new Promise<string>((resolve) => {
        resolveReplay = resolve
      })
    })

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    mockApi.callbacks.terminalData.forEach((cb) => {
      cb({ sessionId: 'session_op_1', data: 'live-before-replay' })
    })
    mockApi.callbacks.sessionPresence.forEach((cb) => {
      cb({ sessionId: 'session_op_1', runtimeState: 'exited', runtimeExitCode: 0, runtimeExitReason: 'clean' } as SessionPresenceSnapshot)
    })

    resolveReplay('restored-frame')
    await flushTerminal()
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances.at(-1)
    expect(instance?.writes).toEqual([
      'restored-frame',
      'live-before-replay\r\n\x1b[90m[session exited]\x1b[0m',
    ])
  })

  test('hung replay request eventually falls back and flushes buffered live and exit output', async () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
    try {
      mockApi.getTerminalReplay = vi.fn().mockImplementation(() => {
        return new Promise<string>(() => {})
      })

      const { default: TerminalViewport } = await import('./TerminalViewport.vue')
      mount(TerminalViewport, {
        props: { project: baseProject, session: baseSession },
      })
      await flushTerminal()

      mockApi.callbacks.terminalData.forEach((cb) => {
        cb({ sessionId: 'session_op_1', data: 'live-while-hung' })
      })
      mockApi.callbacks.sessionPresence.forEach((cb) => {
        cb({ sessionId: 'session_op_1', runtimeState: 'exited', runtimeExitCode: 0, runtimeExitReason: 'clean' } as SessionPresenceSnapshot)
      })
      await flushTerminal()

      const { Terminal } = await import('@xterm/xterm')
      const instance = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances.at(-1)
      expect(instance?.writes).toEqual([])

      await vi.advanceTimersByTimeAsync(1_000)
      await flushTerminal()
      await flushTerminal()
      await flushTerminal()

      expect(instance?.writes).toEqual([
        'live-while-hung\r\n\x1b[90m[session exited]\x1b[0m',
      ])
    } finally {
      vi.useRealTimers()
    }
  })

  test('replay fetch failure still flushes buffered and subsequent live data safely', async () => {
    let rejectReplay!: (reason?: unknown) => void
    mockApi.getTerminalReplay = vi.fn().mockImplementation(() => {
      return new Promise<string>((_, reject) => {
        rejectReplay = reject
      })
    })

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    mockApi.callbacks.terminalData.forEach((cb) => {
      cb({ sessionId: 'session_op_1', data: 'buffered chunk' })
    })

    rejectReplay(new Error('replay failed'))
    await flushTerminal()
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances.at(-1)
    expect(instance?.writes).toContain('buffered chunk')

    mockApi.callbacks.terminalData.forEach((cb) => {
      cb({ sessionId: 'session_op_1', data: 'live after failure' })
    })
    await flushTerminal()

    expect(instance?.writes).toContain('live after failure')
  })

  test('calls sendSessionResize after fit even when the Font Loading API is unavailable', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    expect(mockApi.sendSessionResize).toHaveBeenCalledWith(
      'session_op_1',
      80,
      24
    )
  })

  test('switching between running sessions rebuilds terminal bindings for the new session', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    const nextSession: SessionSummary = {
      ...baseSession,
      id: 'session_shell_2',
      type: 'shell',
      title: 'Shell 2',
      recoveryMode: 'fresh-shell',
      externalSessionId: null
    }

    await wrapper.setProps({ session: nextSession })
    await flushTerminal()

    expect(mockApi.sendSessionResize).toHaveBeenCalledWith(
      'session_shell_2',
      80,
      24
    )
  })

  test('only the latest scheduled setup is allowed to instantiate a terminal after a rapid switch', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })

    await wrapper.setProps({
      session: {
        ...baseSession,
        id: 'session_op_2',
        title: 'OpenCode 2'
      }
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instances = (Terminal as unknown as { instances: unknown[] }).instances
    const resizeCallsForSession2 = mockApi.sendSessionResize.mock.calls.filter(
      ([sessionId]) => sessionId === 'session_op_2'
    )

    expect(instances).toHaveLength(1)
    expect(resizeCallsForSession2).toHaveLength(1)
  })

  test('stale replay from a previous session never writes into the newly mounted terminal', async () => {
    let resolveFirstReplay!: (value: string) => void
    const firstReplay = new Promise<string>((resolve) => {
      resolveFirstReplay = resolve
    })

    mockApi.getTerminalReplay = vi
      .fn()
      .mockReturnValueOnce(firstReplay)
      .mockResolvedValueOnce('session-b-frame')

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    await wrapper.setProps({
      session: {
        ...baseSession,
        id: 'session_op_2',
        title: 'OpenCode 2'
      }
    })
    await flushTerminal()

    resolveFirstReplay('session-a-frame')
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instances = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances
    expect(instances.at(-1)?.writes).not.toContain('session-a-frame')
    expect(instances.at(-1)?.writes).toContain('session-b-frame')
  })

  test.each([
    {
      runtimeState: 'created' as const,
      turnState: 'idle' as const,
      turnEpoch: 0,
      lastTurnOutcome: 'none' as const,
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitReason: null
    },
    {
      runtimeState: 'starting' as const,
      turnState: 'idle' as const,
      turnEpoch: 0,
      lastTurnOutcome: 'none' as const,
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitReason: null
    },
    {
      runtimeState: 'alive' as const,
      turnState: 'running' as const,
      turnEpoch: 1,
      lastTurnOutcome: 'none' as const,
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitReason: null
    },
    {
      runtimeState: 'alive' as const,
      turnState: 'idle' as const,
      turnEpoch: 1,
      lastTurnOutcome: 'completed' as const,
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: true,
      runtimeExitReason: null
    },
    {
      runtimeState: 'alive' as const,
      turnState: 'running' as const,
      turnEpoch: 1,
      lastTurnOutcome: 'none' as const,
      blockingReason: 'permission' as const,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitReason: null
    },
    {
      runtimeState: 'alive' as const,
      turnState: 'idle' as const,
      turnEpoch: 1,
      lastTurnOutcome: 'failed' as const,
      blockingReason: null,
      failureReason: 'provider_error' as const,
      hasUnseenCompletion: false,
      runtimeExitReason: null
    },
    {
      runtimeState: 'exited' as const,
      turnState: 'idle' as const,
      turnEpoch: 1,
      lastTurnOutcome: 'none' as const,
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitReason: 'clean' as const
    },
  ])('keeps xterm mounted for %j session states', async (statePatch) => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: {
        project: baseProject,
        session: {
          ...baseSession,
          ...statePatch
        }
      },
    })
    await flushTerminal()

    expect(wrapper.find('.terminal-viewport__xterm').exists()).toBe(true)
  })

  test('state-only changes do not rebuild the terminal instance for the same session', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instances = (Terminal as unknown as { instances: Array<{ writes: string[] }> }).instances
    expect(instances).toHaveLength(1)

    await wrapper.setProps({
      session: {
        ...baseSession,
        turnState: 'running',
        turnEpoch: 1,
        lastTurnOutcome: 'none',
        blockingReason: 'permission',
        summary: 'Waiting for approval'
      }
    })
    await flushTerminal()

    expect(instances).toHaveLength(1)
    expect(wrapper.find('.terminal-viewport__xterm').exists()).toBe(true)

    await wrapper.setProps({
      session: {
        ...baseSession,
        runtimeState: 'exited',
        runtimeExitReason: 'clean',
        runtimeExitCode: 0,
        summary: 'shell exited (0)'
      }
    })
    await flushTerminal()

    expect(instances).toHaveLength(1)
    expect(wrapper.find('.terminal-viewport__xterm').exists()).toBe(true)
  })

  test('defers initial resize until a hidden terminal becomes visible', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: {
        project: baseProject,
        session: baseSession,
        visible: false
      },
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instances = (Terminal as unknown as { instances: unknown[] }).instances
    expect(instances).toHaveLength(1)
    expect(mockApi.sendSessionResize).not.toHaveBeenCalled()

    await wrapper.setProps({ visible: true })
    await flushTerminal()

    expect(mockApi.sendSessionResize).toHaveBeenCalledWith('session_op_1', 80, 24)
  })

  test('refits the existing terminal instead of recreating it when visibility returns', async () => {
    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    const wrapper = mount(TerminalViewport, {
      props: {
        project: baseProject,
        session: baseSession,
        visible: true
      },
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instances = (Terminal as unknown as { instances: unknown[] }).instances
    expect(instances).toHaveLength(1)

    mockApi.sendSessionResize.mockClear()

    await wrapper.setProps({ visible: false })
    await flushTerminal()
    expect(instances).toHaveLength(1)
    expect(mockApi.sendSessionResize).not.toHaveBeenCalled()

    await wrapper.setProps({ visible: true })
    await flushTerminal()

    expect(instances).toHaveLength(1)
    expect(mockApi.sendSessionResize).toHaveBeenCalledWith('session_op_1', 80, 24)
  })

  test('uses terminal settings from settings store for the xterm instance', async () => {
    const settingsStore = useSettingsStore()
    settingsStore.terminal = { fontSize: 18 }

    const { default: TerminalViewport } = await import('./TerminalViewport.vue')
    mount(TerminalViewport, {
      props: { project: baseProject, session: baseSession },
    })
    await flushTerminal()

    const { Terminal } = await import('@xterm/xterm')
    const instance = (Terminal as unknown as { instances: Array<{ options: Record<string, unknown> }> }).instances.at(-1)
    expect(instance?.options.fontSize).toBe(18)
  })

  test('swallows xterm setup failures without leaving an unhandled rejection', async () => {
    const { Terminal } = await import('@xterm/xterm')
    ;(Terminal as unknown as { failOpen: boolean }).failOpen = true
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

    try {
      const { default: TerminalViewport } = await import('./TerminalViewport.vue')
      mount(TerminalViewport, {
        props: { project: baseProject, session: baseSession },
      })
      await flushTerminal()

      expect(errorSpy).toHaveBeenCalledWith('[terminal] Failed to initialize xterm viewport:', expect.any(Error))
    } finally {
      errorSpy.mockRestore()
    }
  })

  test('does not install parser-level scrollback guards for codex sessions', async () => {
    const source = readFileSync(terminalViewportPath, 'utf8')

    expect(source).not.toContain('installScrollbackGuard')
  })

  test('uses terminal subtheme tokens instead of repeated rgba literals in component styles', () => {
    const source = readFileSync(terminalViewportPath, 'utf8')

    expect(source).not.toContain('rgba(226, 232, 240, 0.45)')
    expect(source).not.toContain('rgba(226, 232, 240, 0.5)')
    expect(source).not.toContain('rgba(226, 232, 240, 0.08)')
    expect(source).not.toContain('rgba(226, 232, 240, 0.6)')
    expect(source).not.toContain('rgba(226, 232, 240, 0.35)')
    expect(source).not.toContain('rgba(226, 232, 240, 0.06)')
  })
})
