// @vitest-environment happy-dom
import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import CommandSurface from './CommandSurface.vue'
import TerminalSessionDeck from './TerminalSessionDeck.vue'
import WorkspaceHierarchyPanel from './WorkspaceHierarchyPanel.vue'
import { useWorkspaceStore } from '@renderer/stores/workspaces'
import type { ProjectHierarchyNode } from '@renderer/stores/workspaces'
import type { SessionPresenceSnapshot } from '@shared/observability'
import type { ProjectSummary, SessionSummary } from '@shared/project-session'
import { createSessionSummaryFixture } from '@shared/test-fixtures'

const defaultTitleGenerationContext = {
  prompt: null,
  assistantSnippet: null,
  contextUpdatedAt: null,
  autoGeneratedTurnEpoch: null
}

const hierarchy: ProjectHierarchyNode[] = [
  {
    id: 'project_alpha',
    name: 'infra-control',
    path: 'D:/infra-control',
    createdAt: 'a',
    updatedAt: 'a',
    active: true,
    archivedSessions: [],
    sessions: [
      {
        ...createSessionSummaryFixture({
          id: 'session_1',
          projectId: 'project_alpha',
          type: 'opencode',
          runtimeState: 'alive',
          turnState: 'running',
          turnEpoch: 1,
          lastTurnOutcome: 'none',
          hasUnseenCompletion: false,
          runtimeExitCode: null,
          runtimeExitReason: null,
          lastStateSequence: 1,
          blockingReason: null,
          failureReason: null,
          title: 'deploy gateway',
          summary: 'running',
          titleGenerationContext: defaultTitleGenerationContext,
          recoveryMode: 'resume-external',
          externalSessionId: 'sess_1',
          createdAt: 'a',
          updatedAt: 'a',
          lastActivatedAt: 'a',
          archived: false
        }),
        active: true
      },
      {
        ...createSessionSummaryFixture({
          id: 'session_2',
          projectId: 'project_alpha',
          type: 'codex',
          runtimeState: 'alive',
          turnState: 'idle',
          turnEpoch: 0,
          lastTurnOutcome: 'none',
          hasUnseenCompletion: false,
          runtimeExitCode: null,
          runtimeExitReason: null,
          lastStateSequence: 2,
          blockingReason: null,
          failureReason: null,
          title: 'review release diff',
          summary: 'waiting',
          titleGenerationContext: defaultTitleGenerationContext,
          recoveryMode: 'resume-external',
          externalSessionId: 'sess_2',
          createdAt: 'a',
          updatedAt: 'a',
          lastActivatedAt: 'b',
          archived: false
        }),
        active: false
      }
    ]
  }
]

const activeProject: ProjectSummary = {
  id: 'project_alpha',
  name: 'infra-control',
  path: 'D:/infra-control',
  createdAt: 'a',
  updatedAt: 'a'
}

const activeSession: SessionSummary = createSessionSummaryFixture({
  id: 'session_1',
  projectId: 'project_alpha',
  type: 'opencode',
  runtimeState: 'alive',
  turnState: 'running',
  turnEpoch: 1,
  lastTurnOutcome: 'none',
  hasUnseenCompletion: false,
  runtimeExitCode: null,
  runtimeExitReason: null,
  lastStateSequence: 1,
  blockingReason: null,
  failureReason: null,
  title: 'deploy gateway',
  summary: 'running',
  titleGenerationContext: defaultTitleGenerationContext,
  recoveryMode: 'resume-external',
  externalSessionId: 'sess_1',
  createdAt: 'a',
  updatedAt: 'a',
  lastActivatedAt: 'a',
  archived: false
})

const secondAiSession: SessionSummary = createSessionSummaryFixture({
  id: 'session_2',
  projectId: 'project_alpha',
  type: 'codex',
  runtimeState: 'alive',
  turnState: 'idle',
  turnEpoch: 0,
  lastTurnOutcome: 'none',
  hasUnseenCompletion: false,
  runtimeExitCode: null,
  runtimeExitReason: null,
  lastStateSequence: 2,
  blockingReason: null,
  failureReason: null,
  title: 'review release diff',
  summary: 'waiting',
  titleGenerationContext: defaultTitleGenerationContext,
  recoveryMode: 'resume-external',
  externalSessionId: 'sess_2',
  createdAt: 'a',
  updatedAt: 'a',
  lastActivatedAt: 'b',
  archived: false
})

const shellSession: SessionSummary = createSessionSummaryFixture({
  id: 'session_shell_1',
  projectId: 'project_alpha',
  type: 'shell',
  runtimeState: 'alive',
  turnState: 'idle',
  turnEpoch: 0,
  lastTurnOutcome: 'none',
  hasUnseenCompletion: false,
  runtimeExitCode: null,
  runtimeExitReason: null,
  lastStateSequence: 3,
  blockingReason: null,
  failureReason: null,
  title: 'shell session',
  summary: 'ready',
  titleGenerationContext: defaultTitleGenerationContext,
  recoveryMode: 'fresh-shell',
  externalSessionId: null,
  createdAt: 'a',
  updatedAt: 'a',
  lastActivatedAt: 'c',
  archived: false
})

function createPresenceSnapshot(overrides: Partial<SessionPresenceSnapshot> = {}): SessionPresenceSnapshot {
  return {
    sessionId: 'session_1',
    projectId: 'project_alpha',
    providerId: 'opencode',
    providerLabel: 'OpenCode',
    modelLabel: 'GPT-5',
    phase: 'running',
    runtimeState: 'alive',
    turnState: 'running',
    turnEpoch: 1,
    lastTurnOutcome: 'none',
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    confidence: 'authoritative',
    health: 'healthy',
    blockingReason: null,
    failureReason: null,
    lastAssistantSnippet: null,
    lastEventAt: '2026-04-24T08:00:00.000Z',
    lastEvidenceType: null,
    hasUnreadTurn: false,
    recoveryPointerState: 'trusted',
    evidenceSequence: 1,
    sourceSequence: 1,
    updatedAt: '2026-04-24T08:00:00.000Z',
    ...overrides
  }
}

describe('CommandSurface', () => {
  it('uses the command panel wrapper structure', () => {
    const pinia = createPinia()
    setActivePinia(pinia)
    const store = useWorkspaceStore(pinia)
    store.hydrate({
      activeProjectId: 'project_alpha',
      activeSessionId: 'session_1',
      terminalWebhookPort: 0,
      projects: [activeProject],
      sessions: [activeSession]
    })

    const wrapper = mount(CommandSurface, {
      global: { plugins: [pinia] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1',
      }
    })

    expect(wrapper.find('[data-testid="command-panel"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="command-body"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="command-layout"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="workspace-hierarchy-panel"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="terminal-session-deck"]').exists()).toBe(true)
    expect(wrapper.find('.terminal-viewport').exists()).toBe(true)
  })

  it('derives a visible running status from session state before observability snapshots arrive', () => {
    const pinia = createPinia()
    setActivePinia(pinia)
    const store = useWorkspaceStore(pinia)
    store.hydrate({
      activeProjectId: 'project_alpha',
      activeSessionId: 'session_1',
      terminalWebhookPort: 0,
      projects: [activeProject],
      sessions: [activeSession]
    })

    const wrapper = mount(CommandSurface, {
      global: { plugins: [pinia] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1',
      }
    })

    const statusDot = wrapper.find('[data-testid="session-status-dot"]')

    expect(statusDot.attributes('data-phase')).toBe('running')
    expect(statusDot.attributes('data-tone')).toBe('success')
  })

  it('renders blocked observability in the row dot and keeps the active terminal mounted without a top bar', () => {
    const pinia = createPinia()
    setActivePinia(pinia)
    const store = useWorkspaceStore(pinia)
    store.hydrate({
      activeProjectId: 'project_alpha',
      activeSessionId: 'session_1',
      terminalWebhookPort: 0,
      projects: [activeProject],
      sessions: [activeSession]
    })
    store.sessionPresenceById = {
      session_1: createPresenceSnapshot({
        phase: 'blocked',
        blockingReason: 'permission',
        sourceSequence: 3
      })
    }

    const wrapper = mount(CommandSurface, {
      global: { plugins: [pinia] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1'
      }
    })

    const statusDot = wrapper.find('[data-testid="session-status-dot"]')
    const terminalViewport = wrapper.find('[data-testid="terminal-viewport"]')

    expect(statusDot.attributes('data-phase')).toBe('blocked')
    expect(statusDot.attributes('data-tone')).toBe('warning')
    expect(wrapper.find('[data-testid="terminal-status-bar"]').exists()).toBe(false)
    expect(terminalViewport.exists()).toBe(true)
  })

  it('forwards archiveSession from WorkspaceHierarchyPanel', async () => {
    const pinia = createPinia()
    setActivePinia(pinia)
    const store = useWorkspaceStore(pinia)
    store.hydrate({
      activeProjectId: 'project_alpha',
      activeSessionId: 'session_1',
      terminalWebhookPort: 0,
      projects: [activeProject],
      sessions: [activeSession]
    })

    const wrapper = mount(CommandSurface, {
      global: { plugins: [pinia] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1'
      }
    })

    await wrapper.findComponent(WorkspaceHierarchyPanel).vm.$emit('archiveSession', 'session_1')

    expect(wrapper.emitted('archiveSession')).toEqual([['session_1']])
  })

  it('forwards restartSession from WorkspaceHierarchyPanel', async () => {
    const pinia = createPinia()
    setActivePinia(pinia)
    const store = useWorkspaceStore(pinia)
    store.hydrate({
      activeProjectId: 'project_alpha',
      activeSessionId: 'session_1',
      terminalWebhookPort: 0,
      projects: [activeProject],
      sessions: [activeSession]
    })

    const wrapper = mount(CommandSurface, {
      global: { plugins: [pinia] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1'
      }
    })

    await wrapper.findComponent(WorkspaceHierarchyPanel).vm.$emit('restartSession', 'session_1')

    expect(wrapper.emitted('restartSession')).toEqual([['session_1']])
  })

  it('keeps previously activated AI terminals mounted when switching sessions', async () => {
    const wrapper = mount(CommandSurface, {
      global: { plugins: [createPinia()] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1'
      }
    })

    expect(wrapper.findAll('.terminal-viewport')).toHaveLength(1)

    await wrapper.setProps({
      activeSession: secondAiSession,
      activeSessionId: 'session_2'
    })

    expect(wrapper.findAll('.terminal-viewport')).toHaveLength(2)
    expect(
      wrapper.get('[data-testid="terminal-session-deck-item"][data-session-id="session_1"]').attributes('style')
    ).toContain('display: none;')
  })

  it('keeps shell sessions on the deck ephemeral path', () => {
    const wrapper = mount(CommandSurface, {
      global: { plugins: [createPinia()] },
      props: {
        hierarchy: [{
          ...hierarchy[0],
          sessions: [{ ...shellSession, active: true }]
        }],
        activeProject,
        activeSession: shellSession,
        activeProjectId: 'project_alpha',
        activeSessionId: shellSession.id
      }
    })

    expect(wrapper.find('[data-testid="terminal-session-deck-ephemeral"]').exists()).toBe(true)
    expect(wrapper.findAll('[data-testid="terminal-session-deck-item"]')).toHaveLength(0)
    expect(wrapper.findAll('.terminal-viewport')).toHaveLength(1)
  })

  it('passes top-level visibility through to the terminal session deck', async () => {
    const wrapper = mount(CommandSurface, {
      global: { plugins: [createPinia()] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1',
        visible: true
      }
    })

    expect(wrapper.findComponent(TerminalSessionDeck).props('visible')).toBe(true)

    await wrapper.setProps({ visible: false })

    expect(wrapper.findComponent(TerminalSessionDeck).props('visible')).toBe(false)
  })

  it('forwards openWorkspace from TerminalSessionDeck', async () => {
    const wrapper = mount(CommandSurface, {
      global: { plugins: [createPinia()] },
      props: {
        hierarchy,
        activeProject,
        activeSession,
        activeProjectId: 'project_alpha',
        activeSessionId: 'session_1'
      }
    })

    await wrapper.findComponent(TerminalSessionDeck).vm.$emit('openWorkspace', {
      sessionId: 'session_1',
      target: 'ide'
    })

    expect(wrapper.emitted('openWorkspace')).toEqual([
      [{ sessionId: 'session_1', target: 'ide' }]
    ])
  })
})
