// @vitest-environment happy-dom
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import ArchiveSurface from './ArchiveSurface.vue'
import type { ProjectHierarchyNode } from '@renderer/stores/workspaces'
import { createSessionSummaryFixture } from '@shared/test-fixtures'

const archiveSurfacePath = resolve(dirname(fileURLToPath(import.meta.url)), 'ArchiveSurface.vue')

const defaultTitleGenerationContext = {
  prompt: null,
  assistantSnippet: null,
  contextUpdatedAt: null,
  autoGeneratedTurnEpoch: null
}

function createHierarchyWithArchived(): ProjectHierarchyNode[] {
  return [
    {
      id: 'project-1',
      name: 'Alpha',
      path: 'D:/workspace/alpha',
      createdAt: 'a',
      updatedAt: 'a',
      active: true,
      sessions: [],
      archivedSessions: [
        {
          ...createSessionSummaryFixture({
            id: 'session-archived-1',
            projectId: 'project-1',
            type: 'shell',
            runtimeState: 'exited',
            turnState: 'idle',
            turnEpoch: 0,
            lastTurnOutcome: 'completed',
            runtimeExitCode: 0,
            runtimeExitReason: 'clean',
            lastStateSequence: 1,
            title: 'Old Shell',
            summary: 'done',
            titleGenerationContext: defaultTitleGenerationContext,
            recoveryMode: 'fresh-shell',
            externalSessionId: null,
            createdAt: '2026-04-21T00:00:00.000Z',
            updatedAt: '2026-04-21T00:00:00.000Z',
            lastActivatedAt: '2026-04-21T00:00:00.000Z'
          }),
          archived: true,
          active: false
        }
      ]
    }
  ]
}

describe('ArchiveSurface', () => {
  it('renders archive surface with correct data attributes', () => {
    const wrapper = mount(ArchiveSurface, { props: { hierarchy: [] } })
    expect(wrapper.find('[data-surface="archive"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="surface.archive"]').exists()).toBe(true)
  })

  it('shows empty message when no archived sessions', () => {
    const wrapper = mount(ArchiveSurface, { props: { hierarchy: [] } })
    expect(wrapper.find('.archive-empty').exists()).toBe(true)
  })

  it('renders archived session cards with project metadata', () => {
    const wrapper = mount(ArchiveSurface, {
      props: { hierarchy: createHierarchyWithArchived() }
    })
    expect(wrapper.find('[data-archive-session="session-archived-1"]').exists()).toBe(true)
    expect(wrapper.findAll('[data-testid="archive.session.row"]')).toHaveLength(1)
    expect(wrapper.find('.archive-card__title').text()).toBe('Old Shell')
    expect(wrapper.text()).toContain('Alpha')
    expect(wrapper.text()).toContain('D:/workspace/alpha')
  })

  it('restore button emits restoreSession event', async () => {
    const wrapper = mount(ArchiveSurface, {
      props: { hierarchy: createHierarchyWithArchived() }
    })
    expect(wrapper.find('[data-testid="archive.session.restore"]').exists()).toBe(true)
    await wrapper.find('[data-archive-restore="session-archived-1"]').trigger('click')
    expect(wrapper.emitted('restoreSession')).toHaveLength(1)
    expect(wrapper.emitted('restoreSession')![0]).toEqual(['session-archived-1'])
  })

  it('uses canonical renderer token names instead of deprecated short-form aliases', () => {
    const source = readFileSync(archiveSurfacePath, 'utf8')

    expect(source).not.toContain('var(--surface')
    expect(source).not.toContain('var(--surface-solid')
    expect(source).not.toContain('var(--text-strong')
    expect(source).not.toContain('var(--text)')
    expect(source).not.toContain('var(--muted')
    expect(source).not.toContain('var(--subtle')
    expect(source).not.toContain('var(--line')
    expect(source).not.toContain('var(--accent')
  })
})
