import { vi } from 'vitest'

import type { RendererApi, SessionSummary } from './project-session'

export type SessionSummaryFixture = SessionSummary & {
  parentSessionId: string | null
  createdBySessionId: string | null
}

export function createTitleGenerationContext() {
  return {
    prompt: null,
    assistantSnippet: null,
    contextUpdatedAt: null,
    autoGeneratedTurnEpoch: null
  }
}

export function createSessionSummaryFixture(
  overrides: Partial<SessionSummaryFixture> = {}
): SessionSummaryFixture {
  return {
    id: 'session_1',
    projectId: 'project_1',
    type: 'shell',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'Session',
    summary: '',
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: 't',
    updatedAt: 't',
    lastActivatedAt: 't',
    archived: false,
    parentSessionId: null,
    createdBySessionId: null,
    ...overrides,
    titleGenerationContext: overrides.titleGenerationContext ?? createTitleGenerationContext()
  }
}

function createUpdateState(overrides: Record<string, unknown> = {}) {
  return {
    phase: 'idle',
    currentVersion: '0.1.0',
    availableVersion: null,
    downloadedVersion: null,
    downloadProgressPercent: null,
    lastCheckedAt: null,
    message: null,
    requiresSessionWarning: false,
    ...overrides
  }
}

export function createRendererApiMock(overrides: Partial<RendererApi> = {}): RendererApi {
  const mock: RendererApi = {
    windowsBuildNumber: undefined,
    getBootstrapState: vi.fn().mockResolvedValue({
      activeProjectId: null,
      activeSessionId: null,
      terminalWebhookPort: 0,
      projects: [],
      sessions: []
    }),
    createProject: vi.fn().mockResolvedValue(null),
    deleteProject: vi.fn().mockResolvedValue(undefined),
    createSession: vi.fn().mockResolvedValue(null),
    openWorkspace: vi.fn().mockResolvedValue(undefined),
    setActiveProject: vi.fn().mockResolvedValue(undefined),
    setActiveSession: vi.fn().mockResolvedValue(undefined),
    archiveSession: vi.fn().mockResolvedValue(undefined),
    regenerateSessionTitle: vi.fn().mockResolvedValue(null),
    getTerminalReplay: vi.fn().mockResolvedValue(''),
    sendSessionInput: vi.fn(),
    sendSessionBinaryInput: vi.fn(),
    sendSessionResize: vi.fn().mockResolvedValue(undefined),
    onTerminalData: vi.fn().mockReturnValue(() => {}),
    onMemoryNotification: vi.fn().mockReturnValue(() => {}),
    onTitleGenerationNotification: vi.fn().mockReturnValue(() => {}),
    onSessionEvent: vi.fn().mockReturnValue(() => {}),
    getSessionPresence: vi.fn().mockResolvedValue(null),
    getProjectObservability: vi.fn().mockResolvedValue(null),
    getAppObservability: vi.fn().mockResolvedValue({
      blockedProjectCount: 0,
      failedProjectCount: 0,
      totalUnreadTurns: 0,
      projectsNeedingAttention: [],
      providerHealthSummary: {},
      lastGlobalEventAt: null,
      sourceSequence: 0,
      updatedAt: '0'
    }),
    listSessionObservationEvents: vi.fn().mockResolvedValue({ events: [], nextCursor: null }),
    onSessionPresenceChanged: vi.fn().mockReturnValue(() => {}),
    onProjectObservabilityChanged: vi.fn().mockReturnValue(() => {}),
    onAppObservabilityChanged: vi.fn().mockReturnValue(() => {}),
    getSettings: vi.fn().mockResolvedValue({
      shellPath: '',
      terminal: {},
      providers: {},
      titleGeneration: {
        enabled: false,
        apiKey: '',
        baseUrl: 'https://api.openai.com/v1',
        model: 'gpt-5.4-mini'
      },
      evolverInferenceProvider: 'claude-code',
      evolverExecutionMode: 'workspace-shell',
      workspaceIde: { id: 'vscode', executablePath: '' },
      claudeDangerouslySkipPermissions: false,
      locale: 'en'
    }),
    setSetting: vi.fn().mockResolvedValue(undefined),
    titleGenerationFetchModels: vi.fn().mockResolvedValue([]),
    pickFolder: vi.fn().mockResolvedValue(null),
    pickFile: vi.fn().mockResolvedValue(null),
    detectShell: vi.fn().mockResolvedValue(null),
    detectProvider: vi.fn().mockResolvedValue(null),
    detectVscode: vi.fn().mockResolvedValue(null),
    minimizeWindow: vi.fn().mockResolvedValue(undefined),
    maximizeWindow: vi.fn().mockResolvedValue(undefined),
    closeWindow: vi.fn().mockResolvedValue(undefined),
    isWindowMaximized: vi.fn().mockResolvedValue(false),
    onWindowMaximizeChange: vi.fn().mockReturnValue(() => {}),
    restoreSession: vi.fn().mockResolvedValue(undefined),
    restartSession: vi.fn().mockResolvedValue(undefined),
    listArchivedSessions: vi.fn().mockResolvedValue([]),
    getUpdateState: vi.fn().mockResolvedValue(createUpdateState()),
    checkForUpdates: vi.fn().mockResolvedValue(
      createUpdateState({ phase: 'up-to-date', message: 'You are up to date.' })
    ),
    downloadUpdate: vi.fn().mockResolvedValue(
      createUpdateState({ phase: 'downloaded', downloadedVersion: '0.2.0' })
    ),
    quitAndInstallUpdate: vi.fn().mockResolvedValue(undefined),
    dismissUpdate: vi.fn().mockResolvedValue(undefined),
    uninstallSidecars: vi.fn().mockResolvedValue(undefined),
    listSessionEvidence: vi.fn().mockResolvedValue([]),
    contextExportFullText: vi.fn().mockResolvedValue({
      text: '',
      truncated: false,
      totalTurns: 0
    }),
    contextExportSlimText: vi.fn().mockResolvedValue({
      text: '',
      truncated: false,
      totalTurns: 0
    }),
    onUpdateState: vi.fn().mockReturnValue(() => {}),
    getSidebarState: vi.fn().mockResolvedValue({
      open: false,
      activeTab: 'explorer',
      width: 320,
      sessionListWidth: 240,
    }),
    setSidebarState: vi.fn().mockResolvedValue(undefined),
    fsReadDir: vi.fn().mockResolvedValue([]),
    fsReadFile: vi.fn().mockResolvedValue(''),
    fsWriteFile: vi.fn().mockResolvedValue(undefined),
    fsCreate: vi.fn().mockResolvedValue(undefined),
    fsRename: vi.fn().mockResolvedValue(undefined),
    fsDelete: vi.fn().mockResolvedValue(undefined),
    fsSearch: vi.fn().mockResolvedValue({
      files: [],
      totalMatches: 0,
      truncated: false
    }),
    fsOpenFile: vi.fn().mockResolvedValue(undefined),
    onFsChanged: vi.fn().mockReturnValue(() => {}),
    shellShowItemInFolder: vi.fn().mockResolvedValue(undefined),
    gitStatus: vi.fn().mockResolvedValue({
      branch: 'main',
      ahead: 0,
      behind: 0,
      clean: true,
      entries: [],
      hasConflicts: false
    }),
    gitStage: vi.fn().mockResolvedValue(undefined),
    gitUnstage: vi.fn().mockResolvedValue(undefined),
    gitDiscard: vi.fn().mockResolvedValue(undefined),
    gitCommit: vi.fn().mockResolvedValue(undefined),
    gitPush: vi.fn().mockResolvedValue(undefined),
    gitPull: vi.fn().mockResolvedValue(undefined),
    gitFetch: vi.fn().mockResolvedValue(undefined),
    gitRebase: vi.fn().mockResolvedValue(undefined),
    gitMerge: vi.fn().mockResolvedValue(undefined),
    gitBranches: vi.fn().mockResolvedValue({
      current: 'main',
      locals: ['main'],
      remotes: ['origin/main']
    }),
    gitLog: vi.fn().mockResolvedValue([]),
    gitDiff: vi.fn().mockResolvedValue(''),
    gitCheckout: vi.fn().mockResolvedValue(undefined),
    gitCreateBranch: vi.fn().mockResolvedValue(undefined)
  }

  return Object.assign(mock, overrides)
}
