import { describe, it, expect, afterAll } from 'vitest'
import { readFile, writeFile, rm } from 'node:fs/promises'
import { mkdirSync, mkdtempSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { migrateFromJson } from './migrate-from-json'
import { createDb } from './connection'
import * as schema from './schema'
import { sql } from 'drizzle-orm'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const tmpDirs: string[] = []

function makeTmpDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'stoa-migration-test-'))
  tmpDirs.push(dir)
  return dir
}

function makeDir(dir: string): void {
  mkdirSync(dir, { recursive: true })
}

function writeJson(filePath: string, data: unknown): Promise<void> {
  return writeFile(filePath, JSON.stringify(data, null, 2), 'utf-8')
}

/** Close the underlying better-sqlite3 connection held by a drizzle wrapper. */
function closeDb(db: ReturnType<typeof createDb>): void {
  const raw = (db as unknown as { $client: { close: () => void } }).$client
  raw.close()
}

afterAll(async () => {
  for (const dir of tmpDirs) {
    await rm(dir, { recursive: true, force: true }).catch(() => {
      // On Windows, WAL files may still be locked by the migration's internal
      // connection which we cannot close (migrateFromJson does not expose it).
      // That is fine — temp dirs are cleaned by the OS eventually.
    })
  }
})

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeGlobalJson(overrides?: Partial<{
  activeProjectId: string | null
  activeSessionId: string | null
  projects: unknown[]
  settings: Record<string, unknown>
}>) {
  return {
    version: 4,
    active_project_id: overrides?.activeProjectId ?? null,
    active_session_id: overrides?.activeSessionId ?? null,
    projects: overrides?.projects ?? [makeProjectFixture()],
    settings: overrides?.settings ?? { theme: 'dark', locale: 'en' },
  }
}

function makeProjectFixture(overrides?: Partial<{
  projectId: string
  name: string
  path: string
}>) {
  return {
    project_id: overrides?.projectId ?? 'proj-1',
    name: overrides?.name ?? 'Test Project',
    path: overrides?.path ?? '/tmp/test-project',
    default_session_type: 'shell' as const,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
  }
}

function makeSessionsJson(sessions: unknown[] = [makeSessionFixture()]) {
  return { sessions }
}

function makeSessionFixture(overrides?: Partial<{
  sessionId: string
  projectId: string
  archived: boolean
  type: string
  runtimeState: string
  turnState: string
}>) {
  return {
    session_id: overrides?.sessionId ?? 'sess-1',
    project_id: overrides?.projectId ?? 'proj-1',
    parent_session_id: null,
    created_by_session_id: null,
    type: overrides?.type ?? 'shell',
    title: 'Test Session',
    runtime_state: overrides?.runtimeState ?? 'alive',
    turn_state: overrides?.turnState ?? 'idle',
    turn_epoch: 1,
    last_turn_outcome: 'none',
    blocking_reason: null,
    failure_reason: null,
    has_unseen_completion: false,
    runtime_exit_code: null,
    runtime_exit_reason: null,
    last_state_sequence: 0,
    last_summary: '',
    external_session_id: null,
    title_generation: {
      prompt: null,
      assistantSnippet: null,
      contextUpdatedAt: null,
      autoGeneratedTurnEpoch: null,
    },
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    last_activated_at: null,
    recovery_mode: 'fresh-shell',
    archived: overrides?.archived ?? false,
    subagent_name: null,
    subagent_result_summary: null,
    subagent_input_epoch: 0,
    subagent_latest_input_at: null,
    subagent_latest_input_state_sequence: 0,
    subagent_result: null,
  }
}

function makeMetaSessionJson(overrides?: Partial<{
  activeMetaSessionId: string | null
}>) {
  return {
    version: 1,
    active_meta_session_id: overrides?.activeMetaSessionId ?? 'meta-1',
    sessions: [makeMetaSessionFixture()],
    proposals: [makeMetaProposalFixture()],
    action_logs: [makeMetaActionLogFixture()],
    inspector_target: null,
  }
}

function makeMetaSessionFixture() {
  return {
    session_id: 'meta-1',
    title: 'Meta Session 1',
    status: 'alive',
    backend_session_type: 'claude-code',
    capability_level: 1,
    pending_proposal_count: 1,
    active_target_count: 2,
    last_summary: 'Running',
    last_risk: null,
    backend_session_id: 'ext-meta-1',
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    last_activated_at: null,
    archived: false,
  }
}

function makeMetaProposalFixture() {
  return {
    proposal_id: 'prop-1',
    meta_session_id: 'meta-1',
    kind: 'prompt',
    target_session_ids: ['sess-1'],
    risk_level: 0,
    status: 'pending_approval',
    summary: 'Test proposal',
    reason: '',
    prompt_text: 'Do something',
    preset_name: null,
    snapshot: {},
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    approved_at: null,
    rejected_at: null,
    executed_at: null,
    execution_result: null,
  }
}

function makeMetaActionLogFixture() {
  return {
    action_id: 'log-1',
    meta_session_id: 'meta-1',
    proposal_id: null,
    action: 'created',
    detail: 'Session created',
    created_at: '2025-01-01T00:00:00.000Z',
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('JSON to SQLite Migration', () => {
  it('should migrate projects successfully', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [
        makeProjectFixture({ projectId: 'proj-1', name: 'Alpha', path: projectPath }),
        makeProjectFixture({ projectId: 'proj-2', name: 'Beta', path: '/nonexistent/path' }),
      ],
    }))

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(2)
    expect(report.errors).toHaveLength(0)

    const db = createDb(dbPath)
    try {
      const projects = db.select().from(schema.projects).all()
      expect(projects).toHaveLength(2)
      expect(projects.find(p => p.id === 'proj-1')?.name).toBe('Alpha')
      expect(projects.find(p => p.id === 'proj-2')?.name).toBe('Beta')
    } finally {
      closeDb(db)
    }
  })

  it('should migrate sessions with all fields', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
    }))

    await writeJson(
      join(projectPath, '.stoa', 'sessions.json'),
      makeSessionsJson([
        makeSessionFixture({
          sessionId: 'sess-1',
          projectId: 'proj-1',
          archived: false,
          type: 'claude-code',
          runtimeState: 'exited',
          turnState: 'idle',
        }),
        makeSessionFixture({
          sessionId: 'sess-2',
          projectId: 'proj-1',
          archived: true,
        }),
      ])
    )

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(1)
    expect(report.sessionsMigrated).toBe(2)
    expect(report.errors).toHaveLength(0)

    const db = createDb(dbPath)
    try {
      const sessions = db.select().from(schema.sessions).all()
      expect(sessions).toHaveLength(2)

      const sess1 = sessions.find(s => s.id === 'sess-1')
      expect(sess1).toBeDefined()
      expect(sess1!.projectId).toBe('proj-1')
      expect(sess1!.type).toBe('claude-code')
      expect(sess1!.runtimeState).toBe('exited')
      expect(sess1!.turnState).toBe('idle')
      expect(sess1!.archiveState).toBe('active')
      expect(sess1!.titleGeneration).toBe(JSON.stringify({
        prompt: null,
        assistantSnippet: null,
        contextUpdatedAt: null,
        autoGeneratedTurnEpoch: null,
      }))

      const sess2 = sessions.find(s => s.id === 'sess-2')
      expect(sess2).toBeDefined()
      expect(sess2!.archiveState).toBe('archived')
    } finally {
      closeDb(db)
    }
  })

  it('should migrate settings', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
      settings: {
        theme: 'dark',
        locale: 'en',
        nested: { key: 'value' },
      },
    }))

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.settingsMigrated).toBe(3)
    expect(report.errors).toHaveLength(0)

    const db = createDb(dbPath)
    try {
      const rows = db.select().from(schema.settings).all()
      expect(rows).toHaveLength(3)

      const themeRow = rows.find(r => r.key === 'theme')
      expect(themeRow).toBeDefined()
      expect(JSON.parse(themeRow!.value)).toBe('dark')

      const nestedRow = rows.find(r => r.key === 'nested')
      expect(nestedRow).toBeDefined()
      expect(JSON.parse(nestedRow!.value)).toEqual({ key: 'value' })
    } finally {
      closeDb(db)
    }
  })

  it('should skip corrupt JSON files without failing', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')

    // Write invalid JSON to global.json
    await writeFile(join(stoaDir, 'global.json'), '{ invalid json !!!', 'utf-8')

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(0)
    expect(report.sessionsMigrated).toBe(0)
    expect(report.settingsMigrated).toBe(0)
    expect(report.errors.length).toBeGreaterThanOrEqual(1)
    expect(report.errors[0].file).toContain('global.json')
  })

  it('should skip missing project sessions gracefully', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    // Intentionally do NOT create .stoa/sessions.json

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
    }))

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(1)
    expect(report.sessionsMigrated).toBe(0)
    expect(report.errors).toHaveLength(0)
  })

  it('should handle empty state', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')

    // global.json exists but has no projects or settings
    await writeJson(join(stoaDir, 'global.json'), {
      version: 4,
      active_project_id: null,
      active_session_id: null,
      projects: [],
    })

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(0)
    expect(report.sessionsMigrated).toBe(0)
    expect(report.metaSessionsMigrated).toBe(0)
    expect(report.settingsMigrated).toBe(0)
    expect(report.errors).toHaveLength(0)
  })

  it('should return accurate MigrationReport', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      activeProjectId: 'proj-1',
      activeSessionId: 'sess-1',
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
      settings: { theme: 'light' },
    }))

    await writeJson(
      join(projectPath, '.stoa', 'sessions.json'),
      makeSessionsJson([makeSessionFixture({ sessionId: 'sess-1', projectId: 'proj-1' })])
    )

    await writeJson(join(stoaDir, 'meta-session.json'), makeMetaSessionJson({
      activeMetaSessionId: 'meta-1',
    }))

    const report = await migrateFromJson(stoaDir, dbPath)

    // Count verification
    expect(report.projectsMigrated).toBe(1)
    expect(report.sessionsMigrated).toBe(1)
    expect(report.settingsMigrated).toBe(1)
    expect(report.metaSessionsMigrated).toBe(1)
    expect(report.errors).toHaveLength(0)

    // Verify data landed in DB
    const db = createDb(dbPath)
    try {
      const projectCount = Number(
        db.select({ count: sql<number>`count(*)` }).from(schema.projects).get()?.count ?? 0
      )
      expect(projectCount).toBe(1)

      const sessionCount = Number(
        db.select({ count: sql<number>`count(*)` }).from(schema.sessions).get()?.count ?? 0
      )
      expect(sessionCount).toBe(1)

      const metaSessionCount = Number(
        db.select({ count: sql<number>`count(*)` }).from(schema.metaSessions).get()?.count ?? 0
      )
      expect(metaSessionCount).toBe(1)

      // Active project/session stored in server_config
      const configRows = db.select().from(schema.serverConfig).all()
      const activeProject = configRows.find(r => r.key === 'active_project_id')
      const activeSession = configRows.find(r => r.key === 'active_session_id')
      const activeMeta = configRows.find(r => r.key === 'active_meta_session_id')
      expect(activeProject?.value).toBe('proj-1')
      expect(activeSession?.value).toBe('sess-1')
      expect(activeMeta?.value).toBe('meta-1')
    } finally {
      closeDb(db)
    }

    // Verify backup files were created
    const globalBak = await readFile(join(stoaDir, 'global.json.bak'), 'utf-8')
    expect(JSON.parse(globalBak).version).toBe(4)

    const sessionsBak = await readFile(join(projectPath, '.stoa', 'sessions.json.bak'), 'utf-8')
    expect(JSON.parse(sessionsBak).sessions).toHaveLength(1)

    const metaBak = await readFile(join(stoaDir, 'meta-session.json.bak'), 'utf-8')
    expect(JSON.parse(metaBak).version).toBe(1)
  })

  it('should migrate v3 global state to v4', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    // Write a v3 format global.json
    await writeJson(join(stoaDir, 'global.json'), {
      version: 3,
      active_project_id: 'proj-1',
      active_session_id: 'sess-1',
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
      settings: { theme: 'system' },
    })

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(1)
    expect(report.settingsMigrated).toBe(1)
    expect(report.errors).toHaveLength(0)
  })

  it('should skip unsupported version global state', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')

    await writeJson(join(stoaDir, 'global.json'), {
      version: 2,
      active_project_id: null,
      active_session_id: null,
      projects: [],
    })

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(0)
    expect(report.skipped.length).toBeGreaterThanOrEqual(1)
    const globalSkip = report.skipped.find(s => s.file.includes('global.json'))
    expect(globalSkip).toBeDefined()
    expect(globalSkip!.reason).toContain('Unsupported version')
  })

  it('should handle missing global.json', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    // Do NOT write global.json

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(0)
    expect(report.sessionsMigrated).toBe(0)
    expect(report.skipped.length).toBeGreaterThanOrEqual(1)
    const globalSkip = report.skipped.find(s => s.file.includes('global.json'))
    expect(globalSkip).toBeDefined()
    expect(globalSkip!.reason).toContain('Not found')
  })

  it('should handle corrupt project sessions file', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
    }))

    // Write corrupt JSON to sessions.json
    await writeFile(join(projectPath, '.stoa', 'sessions.json'), 'not json', 'utf-8')

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.projectsMigrated).toBe(1)
    expect(report.sessionsMigrated).toBe(0)
    expect(report.errors.length).toBeGreaterThanOrEqual(1)
    const sessionError = report.errors.find(e => e.file.includes('sessions.json'))
    expect(sessionError).toBeDefined()
  })

  it('should migrate meta-session proposals with valid target session ids', async () => {
    const base = makeTmpDir()
    const stoaDir = join(base, '.stoa')
    makeDir(stoaDir)
    const dbPath = join(base, 'test.db')
    const projectPath = join(base, 'test-project')
    makeDir(join(projectPath, '.stoa'))

    await writeJson(join(stoaDir, 'global.json'), makeGlobalJson({
      projects: [makeProjectFixture({ projectId: 'proj-1', path: projectPath })],
    }))

    await writeJson(
      join(projectPath, '.stoa', 'sessions.json'),
      makeSessionsJson([makeSessionFixture({ sessionId: 'sess-1', projectId: 'proj-1' })])
    )

    await writeJson(join(stoaDir, 'meta-session.json'), {
      version: 1,
      active_meta_session_id: null,
      sessions: [makeMetaSessionFixture()],
      proposals: [
        {
          ...makeMetaProposalFixture(),
          proposal_id: 'prop-1',
          target_session_ids: ['sess-1'],
        },
        {
          ...makeMetaProposalFixture(),
          proposal_id: 'prop-2',
          target_session_ids: [], // Empty — should be skipped
        },
      ],
      action_logs: [makeMetaActionLogFixture()],
      inspector_target: { sessionId: 'sess-1' },
    })

    const report = await migrateFromJson(stoaDir, dbPath)

    expect(report.metaSessionsMigrated).toBe(1)
    expect(report.errors).toHaveLength(0)

    // Proposal with empty targets should be in skipped
    const proposalSkip = report.skipped.find(
      s => s.reason.includes('no target session')
    )
    expect(proposalSkip).toBeDefined()

    const db = createDb(dbPath)
    try {
      const proposals = db.select().from(schema.metaSessionProposals).all()
      expect(proposals).toHaveLength(1)
      expect(proposals[0].id).toBe('prop-1')
      expect(proposals[0].workSessionId).toBe('sess-1')

      // Inspector target should be stored in server_config
      const configRows = db.select().from(schema.serverConfig).all()
      const inspectorTarget = configRows.find(r => r.key === 'meta_inspector_target')
      expect(inspectorTarget).toBeDefined()
      expect(JSON.parse(inspectorTarget!.value)).toEqual({ sessionId: 'sess-1' })

      // Action logs should be present
      const logs = db.select().from(schema.metaSessionActionLogs).all()
      expect(logs).toHaveLength(1)
      expect(logs[0].action).toBe('created')
    } finally {
      closeDb(db)
    }
  })
})
