/**
 * Integration tests for /ctl/ control routes — Phase 2b + Phase 3 stubs.
 *
 * Tests:
 *   GET  /ctl/whoami
 *   GET  /ctl/session/list
 *   GET  /ctl/session/:id/inspect
 *   POST /ctl/session/create
 *
 * Auth validation works via:
 *   - x-stoa-secret (matches ctlSecret) for local-user
 *   - x-stoa-session-id + x-stoa-session-token pair for sessions
 */
import { describe, it, expect, vi } from 'vitest';
import { Hono } from 'hono';
import type { SessionNodeSnapshot, SessionSummary, SessionType } from 'stoa-shared';
import { createControlRoutes, type ControlDeps, type RuntimeBridgeClient } from './control';
import { SessionVisibilityService } from '../services/session-visibility-service';
import { createErrorHandler } from '../middleware/error-handler';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface ControlEnvelope<T> {
  ok: boolean;
  data: T;
  error?: { code: string; message: string; details: Record<string, unknown> };
}

async function parseBody<T>(res: Response): Promise<T> {
  return (await res.json()) as T;
}

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

const NOW = '2026-01-01T00:00:00.000Z';

function makeSessionSummary(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 'session_1',
    projectId: 'project_1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'shell',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'shell-1',
    summary: 'Running',
    titleGenerationContext: {
      prompt: null,
      assistantSnippet: null,
      contextUpdatedAt: null,
      autoGeneratedTurnEpoch: null,
    },
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: NOW,
    updatedAt: NOW,
    lastActivatedAt: NOW,
    archived: false,
    subagentName: null,
    subagentResultSummary: null,
    subagentInputEpoch: undefined,
    subagentLatestInputAt: undefined,
    subagentLatestInputStateSequence: undefined,
    subagentResult: null,
    ...overrides,
  };
}

function makeNodeSnapshot(session: SessionSummary): SessionNodeSnapshot {
  return {
    session: { ...session },
    tree: {
      rootSessionId: session.id,
      depth: 0,
      childCount: 0,
      descendantCount: 0,
    },
  };
}

// ---------------------------------------------------------------------------
// Test deps factory
// ---------------------------------------------------------------------------

function createMockRuntimeBridge(connected = true): RuntimeBridgeClient {
  return {
    sendInput: vi.fn(async () => {}),
    createChildSession: vi.fn(async (req) => makeSessionSummary({ projectId: req.projectId, type: req.type as SessionType })),
    destroySession: vi.fn(async () => {}),
    dispatchSubagent: vi.fn(async () => ({ kind: 'dispatched' })),
    sendSubagentInput: vi.fn(async () => ({ kind: 'accepted' })),
    stopSubagent: vi.fn(async () => ({ kind: 'stopped' })),
    isConnected: vi.fn(() => connected),
  };
}

function createTestDeps(overrides: Partial<ControlDeps> = {}): ControlDeps {
  const session = makeSessionSummary();
  const node = makeNodeSnapshot(session);
  const sessions: SessionNodeSnapshot[] = [node];
  const sessionInput = { send: vi.fn(async () => {}) };
  const visibilityService = new SessionVisibilityService(() => sessions);

  return {
    getSnapshot: vi.fn(() => sessions),
    visibilityService,
    sessionInput,
    createChildSession: vi.fn(async (req) => makeSessionSummary({ projectId: req.projectId, type: req.type })),
    destroySession: vi.fn(async () => {}),
    getTerminalReplay: vi.fn(async () => ''),
    ctlSecret: 'ctl-secret',
    sessionTokenRegistry: new Map([['session_1', 'token_abc']]),
    isCtlEnabled: () => true,
    runtimeBridge: createMockRuntimeBridge(),
    ...overrides,
  };
}

function createTestApp(deps: ControlDeps): Hono {
  const app = new Hono();
  app.onError(createErrorHandler());
  app.route('/ctl', createControlRoutes(deps));
  return app;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Control routes — /ctl/', () => {
  describe('GET /ctl/whoami', () => {
    it('returns local-user when x-stoa-secret matches', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/whoami', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ caller: string }>>(res);
      expect(body.ok).toBe(true);
      expect(body.data.caller).toBe('local-user');
    });

    it('returns session identity when x-stoa-session-id + token match', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/whoami', {
        headers: {
          'x-stoa-session-id': 'session_1',
          'x-stoa-session-token': 'token_abc',
        },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ caller: string; sessionId: string }>>(res);
      expect(body.ok).toBe(true);
      expect(body.data.caller).toBe('session');
      expect(body.data.sessionId).toBe('session_1');
    });

    it('returns 401 when secret is wrong', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/whoami', {
        headers: { 'x-stoa-secret': 'wrong-secret' },
      });
      expect(res.status).toBe(401);
      const body = await parseBody<ControlEnvelope<null>>(res);
      expect(body.ok).toBe(false);
      expect(body.error!.code).toBe('invalid_secret');
    });

    it('returns 401 when session token is wrong', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/whoami', {
        headers: {
          'x-stoa-session-id': 'session_1',
          'x-stoa-session-token': 'wrong-token',
        },
      });
      expect(res.status).toBe(401);
    });

    it('returns 401 with no auth headers', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/whoami');
      expect(res.status).toBe(401);
    });

    it('returns 503 when isCtlEnabled returns false', async () => {
      const app = createTestApp(createTestDeps({
        isCtlEnabled: () => false,
      }));
      const res = await app.request('/ctl/whoami', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(503);
      const body = await parseBody<ControlEnvelope<null>>(res);
      expect(body.error!.code).toBe('disabled');
    });
  });

  describe('GET /ctl/session/list', () => {
    it('returns the list of session nodes', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/list', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ nodes: SessionNodeSnapshot[] }>>(res);
      expect(body.ok).toBe(true);
      expect(body.data.nodes).toHaveLength(1);
      expect(body.data.nodes[0].session.id).toBe('session_1');
    });
  });

  describe('GET /ctl/session/:id/inspect', () => {
    it('returns session node details for known session', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/session_1/inspect', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ node: SessionNodeSnapshot }>>(res);
      expect(body.ok).toBe(true);
      expect(body.data.node.session.id).toBe('session_1');
    });

    it('returns 404 for unknown session', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/unknown_id/inspect', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(404);
      const body = await parseBody<ControlEnvelope<null>>(res);
      expect(body.error!.code).toBe('unknown_session');
    });
  });

  describe('GET /ctl/session/:id/status', () => {
    it('returns session status for known session', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/session_1/status', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ status: { sessionId: string } }>>(res);
      expect(body.ok).toBe(true);
      expect(body.data.status).toBeDefined();
    });
  });

  describe('POST /ctl/session/create', () => {
    it('returns 503 when runtime bridge is not connected', async () => {
      const deps = createTestDeps();
      deps.runtimeBridge = createMockRuntimeBridge(false);
      const app = createTestApp(deps);
      const res = await app.request('/ctl/session/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-stoa-secret': 'ctl-secret',
        },
        body: JSON.stringify({
          projectId: 'project_1',
          type: 'shell',
        }),
      });
      expect(res.status).toBe(503);
    });

    it('returns 400 when type is missing', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-stoa-secret': 'ctl-secret',
        },
        body: JSON.stringify({ projectId: 'project_1' }),
      });
      expect(res.status).toBe(400);
    });

    it('returns 400 when type is invalid', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-stoa-secret': 'ctl-secret',
        },
        body: JSON.stringify({ projectId: 'project_1', type: 'invalid' }),
      });
      expect(res.status).toBe(400);
    });

    it('returns 400 when projectId is missing for local-user', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-stoa-secret': 'ctl-secret',
        },
        body: JSON.stringify({ type: 'shell' }),
      });
      expect(res.status).toBe(400);
    });
  });

  describe('GET /ctl/capabilities', () => {
    it('returns capability list for local-user', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/capabilities', {
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ controlTransport: string; supports: Record<string, unknown> }>>(res);
      expect(body.data.controlTransport).toBe('loopback-http');
      expect(body.data.supports.health).toBe(true);
      expect(body.data.supports.sessionCreate).toBe(true);
    });
  });

  describe('POST /ctl/session/:id/destroy', () => {
    it('returns 503 when runtime bridge is not connected', async () => {
      const deps = createTestDeps();
      deps.runtimeBridge = createMockRuntimeBridge(false);
      const app = createTestApp(deps);
      const res = await app.request('/ctl/session/session_1/destroy', {
        method: 'POST',
        headers: { 'x-stoa-secret': 'ctl-secret' },
      });
      expect(res.status).toBe(503);
    });
  });

  describe('Auth edge cases', () => {
    it('returns 401 for all routes without valid auth', async () => {
      const app = createTestApp(createTestDeps());
      const res = await app.request('/ctl/session/list');
      expect(res.status).toBe(401);
    });

    it('accepts session-id + token pair with session caller identity', async () => {
      const session = makeSessionSummary({ id: 'session_1' });
      const node = makeNodeSnapshot(session);
      const sessions: SessionNodeSnapshot[] = [node];
      const app = createTestApp(createTestDeps({
        getSnapshot: () => sessions,
        sessionTokenRegistry: new Map([['session_1', 'tok-123']]),
      }));
      const res = await app.request('/ctl/session/list', {
        headers: {
          'x-stoa-session-id': 'session_1',
          'x-stoa-session-token': 'tok-123',
        },
      });
      expect(res.status).toBe(200);
      const body = await parseBody<ControlEnvelope<{ nodes: SessionNodeSnapshot[] }>>(res);
      expect(body.data.nodes).toHaveLength(1);
    });
  });
});
