import { defineTopology } from '../contracts/testing-contracts'

export const mobileTopology = defineTopology({
  surface: 'mobile',
  testIds: {
    shell: 'mobile-shell',
    healthDot: 'mobile-health-dot',
    healthBanner: 'mobile-health-banner',
    healthRetry: 'mobile-health-retry',
    workspaceHome: 'mobile-workspace-home',
    globalSearchTrigger: 'mobile-global-search-trigger',
    globalSearchLayer: 'mobile-global-search-layer',
    globalSearchInput: 'mobile-global-search-input',
    globalSearchSessionResult: 'mobile-global-search-session-result',
    globalSearchWorkspaceResult: 'mobile-global-search-workspace-result',
    recentSession: 'mobile-recent-session',
    workspaceRow: 'mobile-workspace-row',
    archiveTool: 'mobile-tool-archive',
    settingsTool: 'mobile-tool-settings',
    sessionList: 'mobile-session-list',
    sessionSearchInput: 'mobile-session-search-input',
    sessionFilterAll: 'mobile-session-filter-all',
    sessionFilterRunning: 'mobile-session-filter-running',
    sessionFilterBlocked: 'mobile-session-filter-blocked',
    sessionFilterRecent: 'mobile-session-filter-recent',
    sessionRow: 'mobile-session-row',
    newSession: 'mobile-new-session',
    newSessionSheet: 'mobile-new-session-sheet',
    sessionTypeOption: 'mobile-session-type-option',
    sessionView: 'mobile-session-view',
    sessionMore: 'mobile-session-more',
    sessionActionsSheet: 'mobile-session-actions-sheet',
    keysHandle: 'mobile-keys-handle',
    keysDismiss: 'mobile-keys-dismiss',
    keysRail: 'mobile-keys-rail',
    keyEsc: 'mobile-key-esc',
    keyTab: 'mobile-key-tab',
    keyUp: 'mobile-key-up',
    keyDown: 'mobile-key-down',
    keySlash: 'mobile-key-slash',
    keyDash: 'mobile-key-dash',
    keyCopy: 'mobile-key-copy',
    keyPaste: 'mobile-key-paste',
    keyEnter: 'mobile-key-enter',
    archive: 'mobile-archive',
    archiveRow: 'mobile-archive-row',
    archiveRestore: 'mobile-archive-restore',
    settings: 'mobile-settings',
    settingsTabs: 'mobile-settings-tabs',
    memoryBanner: 'mobile-memory-banner'
  }
})
