import type { ObservationEvent } from '@shared/observability'
import type {
  AppSettings,
  BootstrapState,
  SessionSummary,
  SessionTitleGenerationContext
} from '@shared/project-session'
import { SessionTitleGenerator } from '@core/session-title-generator'

interface TitleSnapshotSource {
  snapshot: () => BootstrapState
  getSettings: () => AppSettings
}

interface SessionTitleControllerOptions {
  snapshotSource: TitleSnapshotSource
  updateSessionTitleGenerationContext: (
    sessionId: string,
    patch: Partial<SessionTitleGenerationContext>
  ) => Promise<SessionSummary | null>
  updateSessionTitle: (
    sessionId: string,
    title: string,
    options: {
      prompt?: string | null
      assistantSnippet?: string | null
      contextUpdatedAt?: string | null
      autoGeneratedTurnEpoch?: number | null
    }
  ) => Promise<SessionSummary | null>
  generateTitle?: SessionTitleGenerator['generateTitle']
}

export class SessionTitleController {
  private readonly snapshotSource: TitleSnapshotSource
  private readonly updateSessionTitleGenerationContext: SessionTitleControllerOptions['updateSessionTitleGenerationContext']
  private readonly updateSessionTitle: SessionTitleControllerOptions['updateSessionTitle']
  readonly generateTitle: SessionTitleGenerator['generateTitle']

  constructor(options: SessionTitleControllerOptions) {
    this.snapshotSource = options.snapshotSource
    this.updateSessionTitleGenerationContext = options.updateSessionTitleGenerationContext
    this.updateSessionTitle = options.updateSessionTitle
    this.generateTitle = options.generateTitle ?? new SessionTitleGenerator().generateTitle.bind(new SessionTitleGenerator())
  }

  async captureObservation(event: ObservationEvent): Promise<void> {
    if (event.scope !== 'session' || !event.sessionId) {
      return
    }

    const session = this.findSession(event.sessionId)
    if (!session) {
      return
    }

    const patch = deriveTitleContextPatch(session, event)
    if (!patch) {
      return
    }

    await this.updateSessionTitleGenerationContext(event.sessionId, patch)
  }

  async maybeAutoGenerateForCompletedTurn(sessionId: string): Promise<SessionSummary | null> {
    const session = this.findSession(sessionId)
    if (!session) {
      return null
    }

    if (session.lastTurnOutcome !== 'completed' || session.turnState !== 'idle') {
      return null
    }

    if (session.titleGenerationContext.autoGeneratedTurnEpoch !== null) {
      return null
    }

    try {
      const updated = await this.generateAndPersistTitle(session, session.turnEpoch)
      if (updated) {
        return updated
      }
    } catch {
      // Keep the existing host title on automatic generation failures.
    }

    return await this.updateSessionTitleGenerationContext(session.id, {
      autoGeneratedTurnEpoch: session.turnEpoch
    })
  }

  async regenerateSessionTitle(sessionId: string): Promise<SessionSummary | null> {
    const session = this.findSession(sessionId)
    if (!session) {
      return null
    }

    return await this.generateAndPersistTitle(session, session.titleGenerationContext.autoGeneratedTurnEpoch)
  }

  private async generateAndPersistTitle(
    session: SessionSummary,
    autoGeneratedTurnEpoch: number | null
  ): Promise<SessionSummary | null> {
    const project = this.snapshotSource.snapshot().projects.find((candidate) => candidate.id === session.projectId)
    if (!project) {
      return null
    }

    const settings = this.snapshotSource.getSettings().titleGeneration
    const title = await this.generateTitle({
      settings,
      projectName: project.name,
      sessionType: session.type,
      prompt: session.titleGenerationContext.prompt,
      assistantSnippet: session.titleGenerationContext.assistantSnippet
    })

    if (!title) {
      return null
    }

    return await this.updateSessionTitle(session.id, title, {
      prompt: session.titleGenerationContext.prompt,
      assistantSnippet: session.titleGenerationContext.assistantSnippet,
      contextUpdatedAt: session.titleGenerationContext.contextUpdatedAt,
      autoGeneratedTurnEpoch
    })
  }

  private findSession(sessionId: string): SessionSummary | null {
    return this.snapshotSource.snapshot().sessions.find((candidate) => candidate.id === sessionId) ?? null
  }
}

function deriveTitleContextPatch(
  session: SessionSummary,
  event: ObservationEvent
): Partial<SessionTitleGenerationContext> | null {
  const prompt = typeof event.payload.prompt === 'string' && event.payload.prompt.trim()
    ? event.payload.prompt.trim()
    : undefined
  const snippet = typeof event.payload.snippet === 'string' && event.payload.snippet.trim()
    ? event.payload.snippet.trim()
    : undefined

  if (prompt === undefined && snippet === undefined) {
    return null
  }

  return {
    prompt: prompt ?? session.titleGenerationContext.prompt,
    assistantSnippet: snippet ?? session.titleGenerationContext.assistantSnippet,
    contextUpdatedAt: event.occurredAt
  }
}
