import { describe, expect, test, vi } from 'vitest'
import type { ObservationEvent } from '@shared/observability'
import type {
  AppSettings,
  SessionSummary,
  SessionTitleGenerationNotification
} from '@shared/project-session'
import { createSessionSummaryFixture } from '@shared/test-fixtures'
import { SessionTitleController } from './session-title-controller'

function createSession(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return createSessionSummaryFixture({
    id: 'session_1',
    projectId: 'project_1',
    type: 'codex',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 1,
    lastTurnOutcome: 'completed',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: true,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 2,
    title: 'codex-alpha',
    summary: 'Turn complete',
    titleGenerationContext: {
      prompt: 'fix the restart race',
      assistantSnippet: 'Patched restart sequencing and added tests.',
      contextUpdatedAt: '2026-05-18T09:00:00.000Z',
      autoGeneratedTurnEpoch: null
    },
    recoveryMode: 'resume-external',
    externalSessionId: 'external-1',
    createdAt: '2026-05-18T08:55:00.000Z',
    updatedAt: '2026-05-18T09:00:00.000Z',
    lastActivatedAt: '2026-05-18T09:00:00.000Z',
    archived: false,
    ...overrides
  })
}

function createObservationEvent(overrides: Partial<ObservationEvent> = {}): ObservationEvent {
  return {
    eventId: 'event-1',
    eventVersion: 1,
    sequence: 2,
    occurredAt: '2026-05-18T09:00:00.000Z',
    ingestedAt: '2026-05-18T09:00:00.000Z',
    scope: 'session',
    projectId: 'project_1',
    sessionId: 'session_1',
    providerId: 'codex',
    category: 'presence',
    type: 'presence.complete',
    severity: 'attention',
    retention: 'critical',
    source: 'provider-adapter',
    correlationId: null,
    dedupeKey: null,
    payload: {
      summary: 'Turn complete'
    },
    ...overrides
  }
}

const titleSettings: AppSettings['titleGeneration'] = {
  enabled: true,
  apiKey: 'sk-title',
  baseUrl: 'https://api.openai.com/v1',
  model: 'gpt-5.4-mini'
}

function createNotification(
  overrides: Partial<SessionTitleGenerationNotification> = {}
): SessionTitleGenerationNotification {
  return {
    sessionId: 'session_1',
    projectId: 'project_1',
    trigger: 'manual',
    status: 'pending',
    title: undefined,
    errorMessage: undefined,
    ...overrides
  }
}

function createSettingsSnapshot(): AppSettings {
  return {
    shellPath: '',
    terminal: {},
    providers: {},
    evolverInferenceProvider: 'claude-code',
    evolverExecutionMode: 'workspace-shell',
    titleGeneration: titleSettings,
    workspaceIde: { id: 'vscode', executablePath: '' },
    claudeDangerouslySkipPermissions: false,
    stoaCtlEnabled: false,
    locale: 'en',
    theme: 'system'
  }
}

describe('SessionTitleController', () => {
  test('records first-turn prompt context from assistant evidence', async () => {
    const updateSessionTitleGenerationContext = vi.fn()
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession({
            titleGenerationContext: {
              prompt: null,
              assistantSnippet: null,
              contextUpdatedAt: null,
              autoGeneratedTurnEpoch: null
            }
          })]
        })
      },
      updateSessionTitleGenerationContext,
      updateSessionTitle: vi.fn(),
      generateTitle: vi.fn()
    })

    await controller.captureObservation(createObservationEvent({
      category: 'evidence',
      type: 'evidence.assistant_message',
      payload: {
        prompt: 'fix the restart race',
        snippet: 'Patched restart sequencing and added tests.'
      }
    }))

    expect(updateSessionTitleGenerationContext).toHaveBeenCalledWith('session_1', {
      prompt: 'fix the restart race',
      assistantSnippet: 'Patched restart sequencing and added tests.',
      contextUpdatedAt: '2026-05-18T09:00:00.000Z'
    })
  })

  test('auto-generates title only on the first completed turn', async () => {
    const generateTitle = vi.fn().mockResolvedValue('Fix Restart Race')
    const updateSessionTitle = vi.fn().mockResolvedValue(createSession({
      title: 'Fix Restart Race',
      titleGenerationContext: {
        prompt: 'fix the restart race',
        assistantSnippet: 'Patched restart sequencing and added tests.',
        contextUpdatedAt: '2026-05-18T09:00:00.000Z',
        autoGeneratedTurnEpoch: 1
      }
    }))
    const session = createSession()

    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [session]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle,
      generateTitle
    })

    await controller.maybeAutoGenerateForCompletedTurn(session.id)

    expect(generateTitle).toHaveBeenCalledOnce()
    expect(updateSessionTitle).toHaveBeenCalledWith(session.id, 'Fix Restart Race', {
      prompt: 'fix the restart race',
      assistantSnippet: 'Patched restart sequencing and added tests.',
      contextUpdatedAt: '2026-05-18T09:00:00.000Z',
      autoGeneratedTurnEpoch: 1
    })
  })

  test('skips auto-generation when the completed turn was already auto-titled', async () => {
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession({
            titleGenerationContext: {
              prompt: 'fix the restart race',
              assistantSnippet: 'Patched restart sequencing and added tests.',
              contextUpdatedAt: '2026-05-18T09:00:00.000Z',
              autoGeneratedTurnEpoch: 1
            }
          })]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle: vi.fn(),
      generateTitle: vi.fn()
    })

    await controller.maybeAutoGenerateForCompletedTurn('session_1')

    expect(controller['generateTitle']).not.toHaveBeenCalled()
  })

  test('does not auto-generate again on a later completed turn after the first auto title', async () => {
    const generateTitle = vi.fn()
    const updateSessionTitle = vi.fn()
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession({
            turnEpoch: 2,
            titleGenerationContext: {
              prompt: 'fix the restart race',
              assistantSnippet: 'Patched restart sequencing and added tests.',
              contextUpdatedAt: '2026-05-18T09:05:00.000Z',
              autoGeneratedTurnEpoch: 1
            }
          })]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle,
      generateTitle
    })

    const result = await controller.maybeAutoGenerateForCompletedTurn('session_1')

    expect(result).toBeNull()
    expect(generateTitle).not.toHaveBeenCalled()
    expect(updateSessionTitle).not.toHaveBeenCalled()
  })

  test('marks the first completed turn as attempted when auto-generation returns no title', async () => {
    const generateTitle = vi.fn().mockResolvedValue(null)
    const updateSessionTitleGenerationContext = vi.fn().mockResolvedValue(createSession({
      titleGenerationContext: {
        prompt: 'fix the restart race',
        assistantSnippet: 'Patched restart sequencing and added tests.',
        contextUpdatedAt: '2026-05-18T09:00:00.000Z',
        autoGeneratedTurnEpoch: 1
      }
    }))
    const updateSessionTitle = vi.fn()
    const session = createSession()

    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [session]
        })
      },
      updateSessionTitleGenerationContext,
      updateSessionTitle,
      generateTitle
    })

    const result = await controller.maybeAutoGenerateForCompletedTurn(session.id)

    expect(result?.titleGenerationContext.autoGeneratedTurnEpoch).toBe(1)
    expect(generateTitle).toHaveBeenCalledOnce()
    expect(updateSessionTitle).not.toHaveBeenCalled()
    expect(updateSessionTitleGenerationContext).toHaveBeenCalledWith(session.id, {
      autoGeneratedTurnEpoch: 1
    })
  })

  test('swallows automatic generation errors, preserves the current title, and marks the first turn as attempted', async () => {
    const updateSessionTitleGenerationContext = vi.fn().mockResolvedValue(createSession({
      title: 'codex-alpha',
      titleGenerationContext: {
        prompt: 'fix the restart race',
        assistantSnippet: 'Patched restart sequencing and added tests.',
        contextUpdatedAt: '2026-05-18T09:00:00.000Z',
        autoGeneratedTurnEpoch: 1
      }
    }))
    const updateSessionTitle = vi.fn()
    const session = createSession()

    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [session]
        })
      },
      updateSessionTitleGenerationContext,
      updateSessionTitle,
      generateTitle: vi.fn().mockRejectedValue(new Error('Title generation failed with status 401'))
    })

    const result = await controller.maybeAutoGenerateForCompletedTurn(session.id)

    expect(result?.title).toBe('codex-alpha')
    expect(updateSessionTitle).not.toHaveBeenCalled()
    expect(updateSessionTitleGenerationContext).toHaveBeenCalledWith(session.id, {
      autoGeneratedTurnEpoch: 1
    })
  })

  test('manual regeneration always overwrites the title when generation succeeds', async () => {
    const generateTitle = vi.fn().mockResolvedValue('Rebuild Hook Title Flow')
    const onNotification = vi.fn()
    const updatedSession = createSession({
      title: 'Rebuild Hook Title Flow',
      titleGenerationContext: {
        prompt: 'fix the restart race',
        assistantSnippet: 'Patched restart sequencing and added tests.',
        contextUpdatedAt: '2026-05-18T09:00:00.000Z',
        autoGeneratedTurnEpoch: 1
      }
    })
    const updateSessionTitle = vi.fn().mockResolvedValue(updatedSession)
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession()]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle,
      generateTitle,
      onNotification
    })

    const result = await controller.regenerateSessionTitle('session_1')

    expect(result?.title).toBe('Rebuild Hook Title Flow')
    expect(generateTitle).toHaveBeenCalledOnce()
    expect(updateSessionTitle).toHaveBeenCalledOnce()
    expect(onNotification.mock.calls).toEqual([
      [createNotification()],
      [createNotification({
        status: 'success',
        title: 'Rebuild Hook Title Flow'
      })]
    ])
  })

  test('manual regeneration returns null when no prompt or assistant context is available', async () => {
    const generateTitle = vi.fn().mockResolvedValue(null)
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession({
            titleGenerationContext: {
              prompt: null,
              assistantSnippet: null,
              contextUpdatedAt: null,
              autoGeneratedTurnEpoch: null
            }
          })]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle: vi.fn(),
      generateTitle
    })

    const result = await controller.regenerateSessionTitle('session_1')

    expect(result).toBeNull()
    expect(generateTitle).toHaveBeenCalledOnce()
  })

  test('manual regeneration still surfaces generator errors to the caller', async () => {
    const onNotification = vi.fn()
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession()]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle: vi.fn(),
      generateTitle: vi.fn().mockRejectedValue(new Error('Title generation failed with status 401')),
      onNotification
    })

    await expect(controller.regenerateSessionTitle('session_1')).rejects.toThrow('Title generation failed with status 401')
    expect(onNotification.mock.calls).toEqual([
      [createNotification()],
      [createNotification({
        status: 'error',
        errorMessage: 'Title generation failed with status 401'
      })]
    ])
  })

  test('automatic generation emits only success notification when title generation succeeds', async () => {
    const generateTitle = vi.fn().mockResolvedValue('Fix Restart Race')
    const onNotification = vi.fn()
    const updateSessionTitle = vi.fn().mockResolvedValue(createSession({
      title: 'Fix Restart Race',
      titleGenerationContext: {
        prompt: 'fix the restart race',
        assistantSnippet: 'Patched restart sequencing and added tests.',
        contextUpdatedAt: '2026-05-18T09:00:00.000Z',
        autoGeneratedTurnEpoch: 1
      }
    }))
    const session = createSession()

    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [session]
        })
      },
      updateSessionTitleGenerationContext: vi.fn(),
      updateSessionTitle,
      generateTitle,
      onNotification
    })

    await controller.maybeAutoGenerateForCompletedTurn(session.id)

    expect(onNotification).toHaveBeenCalledTimes(1)
    expect(onNotification).toHaveBeenCalledWith(createNotification({
      trigger: 'automatic',
      status: 'success',
      title: 'Fix Restart Race'
    }))
  })

  test('automatic generation does not notify when no title is produced', async () => {
    const onNotification = vi.fn()
    const controller = new SessionTitleController({
      snapshotSource: {
        getSettings: () => createSettingsSnapshot(),
        snapshot: () => ({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'alpha', path: 'D:/alpha', createdAt: 't', updatedAt: 't' }],
          sessions: [createSession()]
        })
      },
      updateSessionTitleGenerationContext: vi.fn().mockResolvedValue(createSession()),
      updateSessionTitle: vi.fn(),
      generateTitle: vi.fn().mockResolvedValue(null),
      onNotification
    })

    await controller.maybeAutoGenerateForCompletedTurn('session_1')

    expect(onNotification).not.toHaveBeenCalled()
  })
})
