// @vitest-environment happy-dom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { mount, type VueWrapper } from '@vue/test-utils'
import { createPinia, setActivePinia, type Pinia } from 'pinia'
import { useWorkspaceStore } from '@renderer/stores/workspaces'
import { useUpdateStore } from '@renderer/stores/update'
import { createRendererApiMock } from '@shared/test-fixtures'
import App from './App.vue'
import type {
  BootstrapState,
  MemoryNotificationEvent,
  ProjectSummary,
  RendererApi,
  SessionGraphEvent,
  SessionSummary,
  SessionTitleGenerationNotification
} from '@shared/project-session'
import type { SessionPresenceSnapshot } from '@shared/observability'
import type { UpdateState } from '@shared/update-state'

const mockBootstrapState: BootstrapState = {
  activeProjectId: null,
  activeSessionId: null,
  terminalWebhookPort: 0,
  projects: [],
  sessions: []
}

const mockCreatedProject: ProjectSummary = {
  id: 'new_project',
  name: 'test',
  path: '/test',
  createdAt: 'x',
  updatedAt: 'x'
}

function createTitleGenerationContext() {
  return {
    prompt: null,
    assistantSnippet: null,
    contextUpdatedAt: null,
    autoGeneratedTurnEpoch: null
  }
}

function createSessionSummary(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 's1',
    projectId: 'p1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'shell',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    blockingReason: null,
    failureReason: null,
    title: 'S',
    summary: '',
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: 't',
    updatedAt: 't',
    lastActivatedAt: 't',
    archived: false,
    ...overrides,
    titleGenerationContext: overrides.titleGenerationContext ?? createTitleGenerationContext()
  }
}

const mockCreatedSession: SessionSummary = createSessionSummary({
  id: 'new_session',
  projectId: 'new_project',
  title: 'test',
  createdAt: 'x',
  updatedAt: 'x',
  lastActivatedAt: 'x'
})

function createSessionPresenceSnapshot(
  overrides: Partial<SessionPresenceSnapshot> = {}
): SessionPresenceSnapshot {
  return {
    sessionId: 'session_1',
    projectId: 'project_1',
    providerId: 'claude-code',
    providerLabel: 'Claude Code',
    modelLabel: 'Sonnet',
    phase: 'running',
    runtimeState: 'alive',
    turnState: 'running',
    turnEpoch: 1,
    lastTurnOutcome: 'none',
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    confidence: 'authoritative',
    health: 'healthy',
    blockingReason: null,
    failureReason: null,
    lastAssistantSnippet: null,
    lastEventAt: '2026-04-24T08:00:00.000Z',
    lastEvidenceType: null,
    hasUnreadTurn: false,
    recoveryPointerState: 'trusted',
    evidenceSequence: 1,
    sourceSequence: 1,
    updatedAt: '2026-04-24T08:00:00.000Z',
    ...overrides
  }
}

function createUpdateState(overrides: Partial<UpdateState> = {}): UpdateState {
  return {
    phase: 'idle',
    currentVersion: '0.1.0',
    availableVersion: null,
    downloadedVersion: null,
    downloadProgressPercent: null,
    lastCheckedAt: null,
    message: null,
    requiresSessionWarning: false,
    ...overrides
  }
}

function createMemoryNotification(overrides: Partial<MemoryNotificationEvent> = {}): MemoryNotificationEvent {
  return {
    id: 'memory-toast-1',
    projectId: 'project_1',
    sessionId: 'session_1',
    kind: 'recall',
    status: 'success',
    title: 'Memory recalled',
    message: 'Relevant Evolver context was injected for this turn.',
    createdAt: '2026-04-29T02:00:00.000Z',
    ...overrides
  }
}

function createTitleGenerationNotification(
  overrides: Partial<SessionTitleGenerationNotification> = {}
): SessionTitleGenerationNotification {
  return {
    projectId: 'project_1',
    sessionId: 'session_1',
    trigger: 'manual',
    status: 'pending',
    ...overrides
  }
}

async function flush(): Promise<void> {
  await new Promise((r) => setTimeout(r, 0))
  await new Promise((r) => setTimeout(r, 0))
}

function setupStoa(overrides: Partial<RendererApi> = {}) {
  window.stoa = createRendererApiMock({
    getBootstrapState: vi.fn().mockResolvedValue({ ...mockBootstrapState, projects: [], sessions: [] }),
    createProject: vi.fn().mockResolvedValue({ ...mockCreatedProject }),
    createSession: vi.fn().mockResolvedValue({ ...mockCreatedSession }),
    regenerateSessionTitle: vi.fn().mockResolvedValue(createSessionSummary({
      id: 's1',
      projectId: 'p1',
      title: 'Regenerated Title'
    })),
    getAppObservability: vi.fn().mockResolvedValue({
      blockedProjectCount: 0,
      failedProjectCount: 0,
      totalUnreadTurns: 0,
      projectsNeedingAttention: [],
      providerHealthSummary: {},
      lastGlobalEventAt: null,
      sourceSequence: 0,
      updatedAt: 'x'
    }),
    getSettings: vi.fn().mockResolvedValue({
      shellPath: '',
      terminal: {},
      providers: {},
      titleGeneration: {
        enabled: false,
        apiKey: '',
        baseUrl: 'https://api.openai.com/v1',
        model: 'gpt-5.4-mini'
      },
      workspaceIde: { id: 'vscode', executablePath: '' },
      evolverInferenceProvider: 'claude-code',
      evolverExecutionMode: 'workspace-shell',
      claudeDangerouslySkipPermissions: false,
      locale: 'en'
    }),
    getUpdateState: vi.fn().mockResolvedValue(createUpdateState()),
    checkForUpdates: vi.fn().mockResolvedValue(createUpdateState({ phase: 'up-to-date', message: 'You are up to date.' })),
    downloadUpdate: vi.fn().mockResolvedValue(createUpdateState({ phase: 'downloaded', downloadedVersion: '0.2.0' })),
    contextExportFullText: vi.fn().mockResolvedValue({ text: '', truncated: false, totalTurns: 0 }),
    contextExportSlimText: vi.fn().mockResolvedValue({ text: '', truncated: false, totalTurns: 0 }),
    ...overrides
  })
}

function mountApp(pinia: Pinia) {
  return mount(App, {
    global: {
      plugins: [pinia],
      stubs: {
        AppShell: false,
        TerminalViewport: {
          name: 'TerminalViewport',
          template: '<div data-testid="terminal-viewport-stub" />'
        }
      }
    }
  })
}

describe('App (root)', () => {
  let wrapper: VueWrapper | undefined
  let pinia: Pinia

  beforeEach(() => {
    pinia = createPinia()
    setActivePinia(pinia)
    setupStoa()
  })

  afterEach(async () => {
    if (wrapper) {
      wrapper.unmount()
      wrapper = undefined
    }
    await flush()
  })

  describe('bootstrap', () => {
    it('renders a full-height root wrapper so AppShell can inherit window height', async () => {
      wrapper = await mountApp(pinia)
      await flush()

      const root = wrapper.get('.app-root')
      expect(root.classes()).toEqual(expect.arrayContaining(['h-full', 'flex', 'flex-col']))
    })

    it('on mount calls window.stoa.getBootstrapState', async () => {
      wrapper = await mountApp(pinia)
      expect(window.stoa.getBootstrapState).toHaveBeenCalledOnce()
    })

    it('on mount hydrates store with bootstrap data', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 42,
        projects: [{ id: 'p1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Sess' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.projects).toHaveLength(1)
      expect(store.activeProjectId).toBe('p1')
      expect(store.activeSessionId).toBe('s1')
    })

    it('does not fetch a separate archived session list on mount', async () => {
      wrapper = await mountApp(pinia)
      await flush()

      expect(window.stoa.listArchivedSessions).not.toHaveBeenCalled()
    })

    it('on mount fetches initial update state', async () => {
      const initialState = createUpdateState({ phase: 'available', availableVersion: '0.2.0' })
      setupStoa({ getUpdateState: vi.fn().mockResolvedValue(initialState) })

      wrapper = await mountApp(pinia)
      await flush()

      expect(window.stoa.getUpdateState).toHaveBeenCalledOnce()
      expect(useUpdateStore(pinia).state.availableVersion).toBe('0.2.0')
    })

    it('on mount subscribes to pushed update state events', async () => {
      const onUpdateState = vi.fn().mockReturnValue(() => {})
      setupStoa({ onUpdateState })

      wrapper = await mountApp(pinia)
      await flush()

      expect(onUpdateState).toHaveBeenCalledOnce()
    })

    it('on mount subscribes to pushed memory notifications', async () => {
      const onMemoryNotification = vi.fn().mockReturnValue(() => {})
      setupStoa({ onMemoryNotification })

      wrapper = await mountApp(pinia)
      await flush()

      expect(onMemoryNotification).toHaveBeenCalledOnce()
    })

    it('on mount subscribes to pushed title-generation notifications', async () => {
      const onTitleGenerationNotification = vi.fn().mockReturnValue(() => {})
      setupStoa({ onTitleGenerationNotification })

      wrapper = await mountApp(pinia)
      await flush()

      expect(onTitleGenerationNotification).toHaveBeenCalledOnce()
    })

    it('on mount subscribes to pushed session events', async () => {
      const onSessionEvent = vi.fn().mockReturnValue(() => {})
      setupStoa({ onSessionEvent })

      wrapper = await mountApp(pinia)
      await flush()

      expect(onSessionEvent).toHaveBeenCalledOnce()
    })

    it('on mount can bootstrap through a window.stoa web adapter without preload-specific assumptions', async () => {
      const onSessionGraphEvent = vi.fn().mockReturnValue(() => {})
      setupStoa({
        onSessionGraphEvent,
        onSessionEvent: vi.fn().mockReturnValue(() => {})
      })

      wrapper = await mountApp(pinia)
      await flush()

      expect(window.stoa.getBootstrapState).toHaveBeenCalledOnce()
      expect(onSessionGraphEvent).toHaveBeenCalledOnce()
    })

    it('applies pushed update state from the bridge', async () => {
      let listener: ((state: UpdateState) => void) | undefined
      setupStoa({
        onUpdateState: vi.fn().mockImplementation((callback: (state: UpdateState) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()
      listener?.(createUpdateState({ phase: 'downloaded', downloadedVersion: '0.2.0' }))
      await flush()

      expect(useUpdateStore(pinia).state.phase).toBe('downloaded')
      expect(useUpdateStore(pinia).state.downloadedVersion).toBe('0.2.0')
    })

    it('renders a pushed memory notification for the active session', async () => {
      let listener: ((event: MemoryNotificationEvent) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'project_1',
        activeSessionId: 'session_1',
        terminalWebhookPort: 0,
        projects: [{ id: 'project_1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 'session_1', projectId: 'project_1', title: 'Claude Session' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onMemoryNotification: vi.fn().mockImplementation((callback: (event: MemoryNotificationEvent) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()
      listener?.(createMemoryNotification())
      await flush()

      expect(wrapper.get('[data-testid="memory-toast-host"]').text()).toContain('Memory recalled')
      expect(wrapper.get('[data-testid="memory-toast"]').text()).toContain(
        'Relevant Evolver context was injected for this turn.'
      )
    })

    it('ignores pushed memory notifications for inactive sessions', async () => {
      let listener: ((event: MemoryNotificationEvent) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'project_1',
        activeSessionId: 'session_1',
        terminalWebhookPort: 0,
        projects: [{ id: 'project_1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 'session_1', projectId: 'project_1', title: 'Claude Session' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onMemoryNotification: vi.fn().mockImplementation((callback: (event: MemoryNotificationEvent) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()
      listener?.(createMemoryNotification({ sessionId: 'session_2' }))
      await flush()

      expect(wrapper.find('[data-testid="memory-toast-host"]').exists()).toBe(false)
    })

    it('renders pushed title-generation notifications for the active session', async () => {
      let listener: ((event: SessionTitleGenerationNotification) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'project_1',
        activeSessionId: 'session_1',
        terminalWebhookPort: 0,
        projects: [{ id: 'project_1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 'session_1', projectId: 'project_1', title: 'Claude Session' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onTitleGenerationNotification: vi.fn().mockImplementation((callback: (event: SessionTitleGenerationNotification) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()
      listener?.(createTitleGenerationNotification())
      await flush()

      const host = wrapper.get('[data-testid="memory-toast-host"]')
      expect(host.text()).toContain('Generating session title')
      expect(host.text()).toContain('Summarizing the latest turn for "Claude Session".')
    })

    it('renders pushed title-generation notifications even when the session is inactive', async () => {
      let listener: ((event: SessionTitleGenerationNotification) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'project_1',
        activeSessionId: 'session_1',
        terminalWebhookPort: 0,
        projects: [{ id: 'project_1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 'session_1', projectId: 'project_1', title: 'Claude Session' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onTitleGenerationNotification: vi.fn().mockImplementation((callback: (event: SessionTitleGenerationNotification) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()
      listener?.(createTitleGenerationNotification({
        sessionId: 'session_2',
        projectId: 'project_1',
        trigger: 'automatic',
        status: 'success',
        title: 'Updated From Background'
      }))
      await flush()

      const host = wrapper.get('[data-testid="memory-toast-host"]')
      expect(host.text()).toContain('Session title generated')
      expect(host.text()).toContain('Sidebar title updated to "Updated From Background".')
    })

    it('reads update state after subscribing so startup sees the latest transition', async () => {
      const getUpdateState = vi
        .fn()
        .mockResolvedValueOnce(createUpdateState({ phase: 'downloaded', downloadedVersion: '0.2.0' }))

      setupStoa({
        getUpdateState,
        onUpdateState: vi.fn().mockReturnValue(() => {})
      })

      wrapper = await mountApp(pinia)
      await flush()

      expect(getUpdateState).toHaveBeenCalledOnce()
      expect(useUpdateStore(pinia).state.phase).toBe('downloaded')
      expect(useUpdateStore(pinia).state.downloadedVersion).toBe('0.2.0')
    })

    it('applies pushed session events to the workspace store', async () => {
      let listener: ((event: { session: SessionSummary }) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Original Title' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onSessionEvent: vi.fn().mockImplementation((callback: (event: { session: SessionSummary }) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()

      listener?.({
        session: createSessionSummary({ id: 's1', projectId: 'p1', title: 'Updated From Main' })
      })
      await flush()

      expect(useWorkspaceStore(pinia).sessions[0]?.title).toBe('Updated From Main')
    })

    it('hydrates without any generic subagent full result body in bootstrap state', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [{
          ...createSessionSummary({
            id: 's1',
            projectId: 'p1',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            subagentResultSummary: {
              status: 'completed',
              title: 'done',
              createdAt: 't',
              updatedAt: 't',
              hasBody: true
            }
          }),
          subagentResult: undefined
        }]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState)
      })

      wrapper = await mountApp(pinia)
      await flush()

      const session = useWorkspaceStore(pinia).sessions[0]
      expect(session?.subagentResultSummary?.hasBody).toBe(true)
      expect(session?.subagentResult).toBeUndefined()
    })

    it('fallback onSessionEvent upserts unknown child sessions when graph bridge is unavailable', async () => {
      let listener: ((event: { session: SessionSummary }) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Root Session' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onSessionGraphEvent: undefined,
        onSessionEvent: vi.fn().mockImplementation((callback: (event: { session: SessionSummary }) => void) => {
          listener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()

      listener?.({
        session: createSessionSummary({
          id: 's2',
          projectId: 'p1',
          parentSessionId: 's1',
          createdBySessionId: 's1',
          title: 'Child Session'
        })
      })
      await flush()

      expect(useWorkspaceStore(pinia).sessions.map((session) => session.id)).toContain('s2')
    })

    it('subscribes to onSessionGraphEvent and applies graph events when available', async () => {
      let graphListener: ((event: SessionGraphEvent) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'Proj', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Original Title' })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onSessionGraphEvent: vi.fn().mockImplementation((callback: (event: SessionGraphEvent) => void) => {
          graphListener = callback
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()

      expect(window.stoa.onSessionGraphEvent).toHaveBeenCalledOnce()

      const graphEvent: SessionGraphEvent = {
        kind: 'updated',
        graphVersion: 1,
        origin: 'session',
        initiatorSessionId: 's1',
        node: {
          session: createSessionSummary({ id: 's1', projectId: 'p1', title: 'Updated Via Graph Event' }),
          tree: { rootSessionId: 's1', depth: 0, childCount: 0, descendantCount: 0 }
        }
      }
      graphListener?.(graphEvent)
      await flush()

      expect(useWorkspaceStore(pinia).sessions[0]?.title).toBe('Updated Via Graph Event')
    })

    it('hydrates observability and applies pushed session presence snapshots on mount', async () => {
      const sessionPresenceListeners: Array<(snapshot: SessionPresenceSnapshot) => void> = []
      const hydratedState: BootstrapState = {
        activeProjectId: 'project_1',
        activeSessionId: 'session_1',
        terminalWebhookPort: 0,
        projects: [{ id: 'project_1', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({
          id: 'session_1',
          projectId: 'project_1',
          type: 'claude-code',
          turnState: 'running',
          turnEpoch: 1,
          title: 'test session',
          summary: 'running',
          recoveryMode: 'resume-external',
          externalSessionId: 'claude-session-1'
        })]
      }

      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        getSessionPresence: vi.fn().mockResolvedValue(createSessionPresenceSnapshot({ sourceSequence: 2 })),
        onSessionPresenceChanged: vi.fn().mockImplementation((listener: (snapshot: SessionPresenceSnapshot) => void) => {
          sessionPresenceListeners.push(listener)
          return () => {}
        })
      })

      wrapper = await mountApp(pinia)
      await flush()

      const store = useWorkspaceStore(pinia)

      expect(window.stoa.getSessionPresence).toHaveBeenCalledWith('session_1')
      expect(window.stoa.onSessionPresenceChanged).toHaveBeenCalledOnce()
      expect(store.activeSessionPresence?.sourceSequence).toBe(2)
      expect(sessionPresenceListeners).toHaveLength(1)

      for (const sessionPresenceListener of sessionPresenceListeners) {
        sessionPresenceListener(createSessionPresenceSnapshot({
          phase: 'blocked',
          blockingReason: 'permission',
          sourceSequence: 3,
          updatedAt: '2026-04-24T08:00:01.000Z'
        }))
      }
      await flush()

      expect(store.activeSessionPresence?.phase).toBe('blocked')
      expect(store.activeSessionPresence?.blockingReason).toBe('permission')
    })
  })

  describe('project selection', () => {
    it('selectProject event calls workspaceStore.setActiveProject with id', async () => {
      wrapper = await mountApp(pinia)
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('selectProject', 'project_1')
      await flush()
      expect(useWorkspaceStore(pinia).activeProjectId).toBe('project_1')
    })

    it('selectProject event calls window.stoa.setActiveProject with id', async () => {
      wrapper = await mountApp(pinia)
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('selectProject', 'project_1')
      expect(window.stoa.setActiveProject).toHaveBeenCalledWith('project_1')
    })
  })

  describe('session selection', () => {
    it('selectSession event calls workspaceStore.setActiveSession with id', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('selectSession', 's1')
      await flush()
      expect(useWorkspaceStore(pinia).activeSessionId).toBe('s1')
    })

    it('selectSession event calls window.stoa.setActiveSession with id', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('selectSession', 's1')
      expect(window.stoa.setActiveSession).toHaveBeenCalledWith('s1')
    })
  })

  describe('project creation', () => {
    it('createProject event adds result to store via addProject', async () => {
      const createProjectMock = vi.fn().mockResolvedValue({ ...mockCreatedProject })
      setupStoa({ createProject: createProjectMock })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()
      expect(createProjectMock).toHaveBeenCalledOnce()
      expect(useWorkspaceStore(pinia).projects).toHaveLength(1)
      expect(useWorkspaceStore(pinia).projects[0].id).toBe('new_project')
    })

    it('createProject event calls window.stoa.createProject with { name, path }', async () => {
      wrapper = await mountApp(pinia)
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()
      expect(window.stoa.createProject).toHaveBeenCalledWith({ name: 'test', path: '/test' })
    })

    it('createProject event sets created project as active', async () => {
      wrapper = await mountApp(pinia)
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()
      expect(useWorkspaceStore(pinia).activeProjectId).toBe('new_project')
    })
  })

  describe('session creation', () => {
    it('createSession event calls window.stoa.createSession with { projectId, type, title }', async () => {
      wrapper = await mountApp(pinia)
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createSession', { projectId: 'new_project', type: 'shell', title: 'test' })
      expect(window.stoa.createSession).toHaveBeenCalledWith({ projectId: 'new_project', type: 'shell', title: 'test' })
    })

    it('createSession event adds result to store via addSession', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'new_project',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'new_project', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
        sessions: []
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createSession', { projectId: 'new_project', type: 'shell', title: 'test' })
      await flush()
      expect(useWorkspaceStore(pinia).sessions).toHaveLength(1)
      expect(useWorkspaceStore(pinia).sessions[0].id).toBe('new_session')
    })

    it('regenerateSessionTitle event calls window.stoa.regenerateSessionTitle and updates the store title', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Original Title' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('regenerateSessionTitle', 's1')
      await flush()

      expect(window.stoa.regenerateSessionTitle).toHaveBeenCalledWith('s1')
      expect(useWorkspaceStore(pinia).sessions[0]?.title).toBe('Regenerated Title')
    })

    it('regenerateSessionTitle shows a pending toast when main pushes a pending notification while the request is in flight', async () => {
      let resolveRequest: ((value: SessionSummary) => void) | undefined
      let listener: ((event: SessionTitleGenerationNotification) => void) | undefined
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', title: 'Original Title' })]
      }
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        onTitleGenerationNotification: vi.fn().mockImplementation((callback: (event: SessionTitleGenerationNotification) => void) => {
          listener = callback
          return () => {}
        }),
        regenerateSessionTitle: vi.fn().mockImplementation(
          () => new Promise<SessionSummary>((resolve) => {
            resolveRequest = resolve
          })
        )
      })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('regenerateSessionTitle', 's1')
      await flush()

      listener?.(createTitleGenerationNotification({
        sessionId: 's1',
        projectId: 'p1',
        trigger: 'manual',
        status: 'pending'
      }))
      await flush()

      const host = wrapper.get('[data-testid="memory-toast-host"]')
      expect(host.text()).toContain('Generating session title')
      expect(host.text()).toContain('Summarizing the latest turn for "Original Title".')

      resolveRequest?.(createSessionSummary({ id: 's1', projectId: 'p1', title: 'Regenerated Title' }))
      await flush()
    })
  })

  describe('session archiving', () => {
    it('archiveSession event updates store and calls window.stoa.archiveSession', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('archiveSession', 's1')
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(window.stoa.archiveSession).toHaveBeenCalledWith('s1')
      expect(store.sessions[0].archived).toBe(true)
      expect(store.activeSessionId).toBeNull()
    })

    it('archiveSession failure preserves the current selection and records error', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1' })]
      }
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        archiveSession: vi.fn().mockRejectedValue(new Error('archive failed'))
      })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('archiveSession', 's1')
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.sessions[0].archived).toBe(false)
      expect(store.activeProjectId).toBe('p1')
      expect(store.activeSessionId).toBe('s1')
      expect(store.lastError).toBe('archive failed')
    })

    it('restoreSession event updates store, re-selects the session, and calls window.stoa.restoreSession', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', archived: true })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('restoreSession', 's1')
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(window.stoa.restoreSession).toHaveBeenCalledWith('s1')
      expect(store.sessions[0].archived).toBe(false)
      expect(store.activeProjectId).toBe('p1')
      expect(store.activeSessionId).toBe('s1')
      expect(store.projectHierarchy[0]!.archivedSessions).toHaveLength(0)
      expect(store.projectHierarchy[0]!.sessions[0]!.id).toBe('s1')
    })

    it('restoreSession failure preserves the previous selection and records error', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: 's1',
        terminalWebhookPort: 0,
        projects: [
          { id: 'p1', name: 'P1', path: '/p1', createdAt: 't', updatedAt: 't' },
          { id: 'p2', name: 'P2', path: '/p2', createdAt: 't', updatedAt: 't' }
        ],
        sessions: [
          createSessionSummary({ id: 's1', projectId: 'p1', archived: false }),
          createSessionSummary({ id: 's2', projectId: 'p2', archived: true })
        ]
      }
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        restoreSession: vi.fn().mockRejectedValue(new Error('restore failed'))
      })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('restoreSession', 's2')
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.sessions.find((session) => session.id === 's2')?.archived).toBe(true)
      expect(store.activeProjectId).toBe('p1')
      expect(store.activeSessionId).toBe('s1')
      expect(store.lastError).toBe('restore failed')
    })

    it('restartSession event updates store and calls window.stoa.restartSession', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'p1',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'p1', name: 'P', path: '/p', createdAt: 't', updatedAt: 't' }],
        sessions: [createSessionSummary({ id: 's1', projectId: 'p1', type: 'opencode', externalSessionId: 'ext-1' })]
      }
      setupStoa({ getBootstrapState: vi.fn().mockResolvedValue(hydratedState) })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('restartSession', 's1')
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(window.stoa.restartSession).toHaveBeenCalledWith('s1')
      expect(store.activeProjectId).toBe('p1')
      expect(store.activeSessionId).toBe('s1')
    })
  })

  describe('workspace quick access', () => {
    it('openWorkspace event calls window.stoa.openWorkspace and clears previous errors', async () => {
      wrapper = await mountApp(pinia)
      await flush()

      const store = useWorkspaceStore(pinia)
      store.lastError = 'previous error'

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('openWorkspace', { sessionId: 's1', target: 'ide' })
      await flush()

      expect(window.stoa.openWorkspace).toHaveBeenCalledWith({ sessionId: 's1', target: 'ide' })
      expect(store.lastError).toBeNull()
    })

    it('openWorkspace failure records the launcher error', async () => {
      setupStoa({
        openWorkspace: vi.fn().mockRejectedValue(new Error('VS Code executable not found'))
      })

      wrapper = await mountApp(pinia)
      await flush()

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('openWorkspace', { sessionId: 's1', target: 'ide' })
      await flush()

      expect(useWorkspaceStore(pinia).lastError).toBe('VS Code executable not found')
    })
  })

  describe('project creation error handling', () => {
    it('when createProject rejects with Error → sets store.lastError to error message', async () => {
      setupStoa({ createProject: vi.fn().mockRejectedValue(new Error('Project path already exists')) })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.lastError).toBe('Project path already exists')
      expect(store.projects).toHaveLength(0)
    })

    it('when createProject rejects with string → sets store.lastError to string', async () => {
      setupStoa({ createProject: vi.fn().mockRejectedValue('some string error') })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.lastError).toBe('some string error')
    })

    it('when createProject returns null → sets store.lastError to null-response message', async () => {
      setupStoa({ createProject: vi.fn().mockResolvedValue(null) })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.lastError).toBe('Failed to create project: no response from main process')
      expect(store.projects).toHaveLength(0)
      expect(store.activeProjectId).toBeNull()
    })

    it('successful createProject clears previous error', async () => {
      setupStoa()

      wrapper = await mountApp(pinia)
      await flush()
      const store = useWorkspaceStore(pinia)
      store.lastError = 'prev error'

      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createProject', { name: 'test', path: '/test' })
      await flush()

      expect(store.lastError).toBeNull()
      expect(store.projects).toHaveLength(1)
      expect(store.projects[0].id).toBe('new_project')
    })
  })

  describe('session creation error handling', () => {
    it('when createSession rejects → sets store.lastError', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'new_project',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'new_project', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
        sessions: []
      }
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        createSession: vi.fn().mockRejectedValue(new Error('Session must belong to an existing project'))
      })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createSession', { projectId: 'new_project', type: 'shell', title: 'test' })
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.lastError).toBe('Session must belong to an existing project')
      expect(store.sessions).toHaveLength(0)
    })

    it('when createSession returns null → sets store.lastError to null-response message', async () => {
      const hydratedState: BootstrapState = {
        activeProjectId: 'new_project',
        activeSessionId: null,
        terminalWebhookPort: 0,
        projects: [{ id: 'new_project', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
        sessions: []
      }
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue(hydratedState),
        createSession: vi.fn().mockResolvedValue(null)
      })

      wrapper = await mountApp(pinia)
      await flush()
      const appShell = wrapper.findComponent({ name: 'AppShell' })
      await appShell.vm.$emit('createSession', { projectId: 'new_project', type: 'shell', title: 'test' })
      await flush()

      const store = useWorkspaceStore(pinia)
      expect(store.lastError).toBe('Failed to create session: no response from main process')
    })
  })

  describe('cleanup', () => {
    it('keeps update listeners active after mount until unmount', async () => {
      const unsubscribeUpdate = vi.fn()
      setupStoa({
        onUpdateState: vi.fn().mockReturnValue(unsubscribeUpdate)
      })

      wrapper = await mountApp(pinia)
      await flush()

      expect(unsubscribeUpdate).not.toHaveBeenCalled()
    })

    it('keeps observability listeners active after mount until unmount', async () => {
      const unsubscribeSessionPresence = vi.fn()
      const unsubscribeProjectObservability = vi.fn()
      const unsubscribeAppObservability = vi.fn()
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
          sessions: [createSessionSummary({
            id: 'session_1',
            projectId: 'project_1',
            type: 'claude-code',
            turnState: 'running',
            turnEpoch: 1,
            title: 'test session',
            summary: 'running',
            recoveryMode: 'resume-external',
            externalSessionId: 'claude-session-1'
          })]
        }),
        onSessionPresenceChanged: vi.fn().mockReturnValue(unsubscribeSessionPresence),
        onProjectObservabilityChanged: vi.fn().mockReturnValue(unsubscribeProjectObservability),
        onAppObservabilityChanged: vi.fn().mockReturnValue(unsubscribeAppObservability)
      })

      wrapper = await mountApp(pinia)
      await flush()

      expect(unsubscribeSessionPresence).not.toHaveBeenCalled()
      expect(unsubscribeProjectObservability).not.toHaveBeenCalled()
      expect(unsubscribeAppObservability).not.toHaveBeenCalled()
    })

    it('unsubscribes update listeners on unmount', async () => {
      const unsubscribeUpdate = vi.fn()
      setupStoa({
        onUpdateState: vi.fn().mockReturnValue(unsubscribeUpdate)
      })

      wrapper = await mountApp(pinia)
      await flush()
      wrapper.unmount()
      wrapper = undefined

      expect(unsubscribeUpdate).toHaveBeenCalledOnce()
    })

    it('unsubscribes title-generation listeners on unmount', async () => {
      const unsubscribeTitleGeneration = vi.fn()
      setupStoa({
        onTitleGenerationNotification: vi.fn().mockReturnValue(unsubscribeTitleGeneration)
      })

      wrapper = await mountApp(pinia)
      await flush()
      wrapper.unmount()
      wrapper = undefined

      expect(unsubscribeTitleGeneration).toHaveBeenCalledOnce()
    })

    it('unsubscribes observability listeners on unmount', async () => {
      const unsubscribeSessionPresence = vi.fn()
      const unsubscribeProjectObservability = vi.fn()
      const unsubscribeAppObservability = vi.fn()
      setupStoa({
        getBootstrapState: vi.fn().mockResolvedValue({
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 0,
          projects: [{ id: 'project_1', name: 'test', path: '/test', createdAt: 't', updatedAt: 't' }],
          sessions: [createSessionSummary({
            id: 'session_1',
            projectId: 'project_1',
            type: 'claude-code',
            turnState: 'running',
            turnEpoch: 1,
            title: 'test session',
            summary: 'running',
            recoveryMode: 'resume-external',
            externalSessionId: 'claude-session-1'
          })]
        }),
        onSessionPresenceChanged: vi.fn().mockReturnValue(unsubscribeSessionPresence),
        onProjectObservabilityChanged: vi.fn().mockReturnValue(unsubscribeProjectObservability),
        onAppObservabilityChanged: vi.fn().mockReturnValue(unsubscribeAppObservability)
      })

      wrapper = await mountApp(pinia)
      await flush()
      wrapper.unmount()
      wrapper = undefined

      expect(unsubscribeSessionPresence).toHaveBeenCalledOnce()
      expect(unsubscribeProjectObservability).toHaveBeenCalledOnce()
      expect(unsubscribeAppObservability).toHaveBeenCalledOnce()
    })
  })
})
