export const IPC_CHANNELS = {
  projectBootstrap: 'project:bootstrap',
  projectCreate: 'project:create',
  projectSetActive: 'project:set-active',
  sessionCreate: 'session:create',
  sessionSetActive: 'session:set-active',
  sessionInput: 'session:input',
  sessionResize: 'session:resize',
  sessionEvent: 'session:event',
  terminalData: 'terminal:data',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  dialogPickFolder: 'dialog:pick-folder',
  dialogPickFile: 'dialog:pick-file',
  settingsDetectShell: 'settings:detect-shell',
  settingsDetectProvider: 'settings:detect-provider',
} as const
