import { describe, expect, test, vi } from 'vitest'
import { createSessionSummaryFixture } from '@shared/test-fixtures'
import { MetaSessionProposalStore } from './meta-session-proposal-store'
import { MetaSessionCommandDispatcher } from './meta-session-command-dispatcher'

const defaultTitleGenerationContext = {
  prompt: null,
  assistantSnippet: null,
  contextUpdatedAt: null,
  autoGeneratedTurnEpoch: null
}

function createWorkSession(lastStateSequence = 17) {
  return createSessionSummaryFixture({
    id: 'session_1',
    projectId: 'project_1',
    type: 'codex',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 4,
    lastTurnOutcome: 'completed',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: true,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence,
    title: 'session one',
    summary: 'Completed but waiting for review.',
    titleGenerationContext: defaultTitleGenerationContext,
    recoveryMode: 'resume-external',
    externalSessionId: 'codex-1',
    createdAt: '2026-05-07T08:00:00.000Z',
    updatedAt: lastStateSequence === 17
      ? '2026-05-07T08:05:00.000Z'
      : '2026-05-07T08:06:00.000Z',
    lastActivatedAt: '2026-05-07T08:05:00.000Z',
    archived: false
  })
}

describe('MetaSessionCommandDispatcher', () => {
  test('creates a proposal instead of directly injecting a freeform prompt when approval is required', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: 'session_1',
            terminalWebhookPort: 43127,
            projects: [],
            sessions: [createWorkSession()]
          }
        }
      },
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const result = await dispatcher.promptWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      text: 'Refactor and edit the code now.'
    })

    expect(result.kind).toBe('approval_required')
    if (result.kind !== 'approval_required') {
      throw new Error('expected approval_required result')
    }
    expect(result.proposal?.status).toBe('pending_approval')
    expect(send).not.toHaveBeenCalled()
  })

  test('treats all freeform prompt injection as approval-gated even when the text is low risk', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: 'session_1',
            terminalWebhookPort: 43127,
            projects: [],
            sessions: [createWorkSession()]
          }
        }
      },
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const result = await dispatcher.promptWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      text: 'Please summarize the current diff and test status.'
    })

    expect(result.kind).toBe('approval_required')
    expect(send).not.toHaveBeenCalled()
  })

  test('rejects proposal dispatch when the proposal has become stale', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    const snapshotSource = {
      snapshot() {
        return {
          activeProjectId: 'project_1',
          activeSessionId: 'session_1',
          terminalWebhookPort: 43127,
          projects: [],
          sessions: [createWorkSession()]
        }
      }
    }
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource,
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const created = await dispatcher.promptWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      text: 'Refactor and edit the code now.'
    })

    if (created.kind !== 'approval_required') {
      throw new Error('expected approval_required result')
    }

    await proposalStore.markStale(created.proposal.id)

    await expect(dispatcher.dispatchProposal(created.proposal.id)).rejects.toThrow(/stale/i)
    expect(send).not.toHaveBeenCalled()
  })

  test('marks a proposal stale when the target session state has changed since proposal creation', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    let lastStateSequence = 17
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: 'session_1',
            terminalWebhookPort: 43127,
            projects: [],
            sessions: [createWorkSession(lastStateSequence)]
          }
        }
      },
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const created = await dispatcher.promptWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      text: 'Refactor and edit the code now.'
    })

    if (created.kind !== 'approval_required') {
      throw new Error('expected approval_required result')
    }

    lastStateSequence = 18

    await expect(dispatcher.dispatchProposal(created.proposal.id)).rejects.toThrow(/stale/i)
    expect(proposalStore.get(created.proposal.id)?.status).toBe('stale')
    expect(send).not.toHaveBeenCalled()
  })

  test('dispatches run-tests-only preset directly without approval', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: 'session_1',
            terminalWebhookPort: 43127,
            projects: [],
            sessions: [createWorkSession()]
          }
        }
      },
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const result = await dispatcher.dispatchPreset({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      presetName: 'run-tests-only'
    })

    expect(result).toEqual({
      kind: 'dispatched',
      presetName: 'run-tests-only'
    })
    expect(send).toHaveBeenCalledWith('session_1', 'Continue by running the project test command only. Do not modify code. Summarize failures and likely causes.\r')
  })

  test('dispatches low-level send-keys input directly without approval', async () => {
    const proposalStore = new MetaSessionProposalStore()
    const send = vi.fn(async () => {})
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: 'session_1',
            terminalWebhookPort: 43127,
            projects: [],
            sessions: [createWorkSession()]
          }
        }
      },
      sessionInput: {
        send
      },
      proposals: proposalStore
    })

    const result = await dispatcher.sendKeysToWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_1',
      data: '1\r'
    })

    expect(result).toEqual({ kind: 'dispatched' })
    expect(send).toHaveBeenCalledWith('session_1', '1\r')
  })

  test('rejects send-keys for unknown sessions', async () => {
    const dispatcher = new MetaSessionCommandDispatcher({
      snapshotSource: {
        snapshot() {
          return {
            activeProjectId: 'project_1',
            activeSessionId: null,
            terminalWebhookPort: 43127,
            projects: [],
            sessions: []
          }
        }
      },
      sessionInput: {
        send: vi.fn(async () => {})
      },
      proposals: new MetaSessionProposalStore()
    })

    await expect(dispatcher.sendKeysToWorkSession({
      metaSessionId: 'meta_session_1',
      targetSessionId: 'session_missing',
      data: '1'
    })).rejects.toThrow(/unknown session/i)
  })
})
