import { afterEach, describe, expect, test } from 'vitest'
import { request } from 'node:http'
import { createSessionControlServer, type SessionControlServerDeps } from './session-control-server'
import type { SessionNodeSnapshot, SessionSummary } from '@shared/project-session'
import type { AuthorityResult } from './session-visibility-service'
import { SessionVisibilityService } from './session-visibility-service'

const servers: Array<ReturnType<typeof createSessionControlServer>> = []

function makeSession(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 'root',
    projectId: 'proj-1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'claude-code',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'root',
    summary: '',
    titleGenerationContext: { prompt: null, assistantSnippet: null, contextUpdatedAt: null, autoGeneratedTurnEpoch: null },
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: '2026-05-29T00:00:00.000Z',
    updatedAt: '2026-05-29T00:00:00.000Z',
    lastActivatedAt: null,
    archived: false,
    ...overrides
  }
}

function makeNode(overrides: Partial<SessionSummary> = {}, treeOverrides: Record<string, unknown> = {}): SessionNodeSnapshot {
  return {
    session: makeSession(overrides),
    tree: {
      rootSessionId: 'root',
      depth: 0,
      childCount: 0,
      descendantCount: 0,
      ...treeOverrides
    }
  }
}

async function get(
  port: number,
  path: string,
  headers: Record<string, string> = {}
): Promise<{ statusCode: number; body: string }> {
  return await new Promise((resolve, reject) => {
    const req = request({ host: '127.0.0.1', port, path, method: 'GET', headers }, (response) => {
      let body = ''
      response.setEncoding('utf8')
      response.on('data', (chunk: string) => { body += chunk })
      response.on('end', () => { resolve({ statusCode: response.statusCode ?? 0, body }) })
    })
    req.on('error', reject)
    req.end()
  })
}

async function post(
  port: number,
  path: string,
  headers: Record<string, string> = {},
  body?: string
): Promise<{ statusCode: number; body: string }> {
  return await new Promise((resolve, reject) => {
    const req = request(
      { host: '127.0.0.1', port, path, method: 'POST', headers: { ...headers, ...(body ? { 'content-type': 'application/json' } : {}) } },
      (response) => {
        let responseBody = ''
        response.setEncoding('utf8')
        response.on('data', (chunk: string) => { responseBody += chunk })
        response.on('end', () => { resolve({ statusCode: response.statusCode ?? 0, body: responseBody }) })
      }
    )
    req.on('error', reject)
    if (body) req.write(body)
    req.end()
  })
}

function makeDeps(overrides: Partial<SessionControlServerDeps> = {}): SessionControlServerDeps {
  const nodes = [
    makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
    makeNode({ id: 'child', parentSessionId: 'root', createdBySessionId: 'root' }, { rootSessionId: 'root', depth: 1 })
  ]
  return {
    getSnapshot: () => nodes,
    visibilityService: {
      visibleSessionIds: () => nodes.map((n) => n.session.id),
      isVisible: () => true,
      checkAuthority: () => ({ allowed: true })
    } as any,
    sessionInput: { send: async () => {} },
    createChildSession: async () => makeSession({ id: 'new-child' }),
    destroySession: async () => {},
    ctlSecret: 'test-secret-1234',
    getTerminalReplay: async () => '',
    sessionTokenRegistry: new Map([
      ['root', 'tok_root_1234'],
      ['child', 'tok_child_5678']
    ]),
    ...overrides
  }
}

async function startServer(deps: SessionControlServerDeps): Promise<{ server: ReturnType<typeof createSessionControlServer>; port: number }> {
  const server = createSessionControlServer(deps)
  servers.push(server)
  const port = await server.start()
  return { server, port }
}

afterEach(async () => {
  while (servers.length > 0) {
    const s = servers.pop()!
    await s.stop()
  }
})

describe('SessionControlServer', () => {
  describe('auth', () => {
    test('rejects requests without credentials', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health')
      expect(res.statusCode).toBe(401)
    })

    test('accepts local-user secret via x-stoa-secret header', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
    })

    test('accepts session auth via x-stoa-session-id + x-stoa-session-token', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(200)
    })

    test('rejects invalid session token', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'wrong-token' })
      expect(res.statusCode).toBe(401)
    })

    test('rejects unknown session id', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health', { 'x-stoa-session-id': 'nonexistent', 'x-stoa-session-token': 'anything' })
      expect(res.statusCode).toBe(401)
    })
  })

  describe('/ctl/health', () => {
    test('returns ok:true', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/health', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.ok).toBe(true)
      expect(body.data).toEqual({ ok: true })
    })
  })

  describe('/ctl/whoami', () => {
    test('returns caller=local-user for secret auth', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/whoami', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.caller).toBe('local-user')
    })

    test('returns caller=session with session info for token auth', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/whoami', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.caller).toBe('session')
      expect(body.data.sessionId).toBe('root')
    })
  })

  describe('/ctl/capabilities', () => {
    test('returns capability list', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/capabilities', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.supports).toBeDefined()
      expect(body.data.supports.sessionStatus).toBe(true)
      expect(body.data.supports.sessionWait).toBe(true)
      expect(body.data.supports.sessionOutput).toBe(true)
      expect(body.data.supports.sessionCompletionReport).toBe(true)
      expect(body.data.controlTransport).toBe('loopback-http')
    })
  })

  describe('/ctl/session/list', () => {
    test('returns session list', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/list', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.nodes).toHaveLength(2)
    })
  })

  describe('/ctl/session/:id/inspect', () => {
    test('returns node snapshot for existing session', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/root/inspect', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.node.session.id).toBe('root')
    })

    test('returns unknown_session for non-existent session', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/nonexistent/inspect', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(404)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('unknown_session')
    })

    test('returns unknown_session when session caller cannot see target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const { port } = await startServer(deps)
      const res = await get(port, '/ctl/session/child/inspect', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(404)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('unknown_session')
    })
  })

  describe('/ctl/session/:id/status', () => {
    test('returns status projection for existing session', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/root/status', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.status.sessionId).toBe('root')
      expect(body.data.status.runtimeState).toBe('alive')
      expect(body.data.status.turnState).toBe('idle')
      expect(body.data.status.phase).toBe('ready')
    })

    test('returns unknown_session for missing status target', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/missing/status', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(404)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('unknown_session')
    })

    test('returns forbidden_authority_scope for status without authority', async () => {
      const { port } = await startServer(makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root'],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      }))
      const res = await get(port, '/ctl/session/child/status', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(403)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('forbidden_authority_scope')
    })
  })

  describe('/ctl/session/:id/output', () => {
    test('returns terminal replay for existing visible session', async () => {
      const { port } = await startServer(makeDeps({
        getTerminalReplay: async (sessionId: string) => `replay:${sessionId}`
      }))
      const res = await get(port, '/ctl/session/child/output', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.output).toEqual({ sessionId: 'child', text: 'replay:child' })
    })

    test('returns forbidden_authority_scope when output is not visible', async () => {
      const { port } = await startServer(makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root'],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      }))
      const res = await get(port, '/ctl/session/child/output', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(403)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('forbidden_authority_scope')
    })
  })

  describe('/ctl/session/:id/completion-report', () => {
    test('returns report for completed session', async () => {
      const { port } = await startServer(makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 4,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: true,
            summary: 'finished'
          }, { rootSessionId: 'root', depth: 1 })
        ]
      }))
      const res = await get(port, '/ctl/session/child/completion-report', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.report).toMatchObject({
        sessionId: 'child',
        parentSessionId: 'root',
        outcome: 'completed',
        summary: 'finished'
      })
    })

    test('returns no_completion_yet for non-terminal session', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/root/completion-report', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(409)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('no_completion_yet')
    })

    test('returns forbidden_authority_scope for report without authority', async () => {
      const { port } = await startServer(makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root'],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      }))
      const res = await get(port, '/ctl/session/child/completion-report', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(403)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('forbidden_authority_scope')
    })
  })

  describe('/ctl/session/:id/wait', () => {
    test('returns completed session output and report', async () => {
      const { port } = await startServer(makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 4,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: true,
            summary: 'finished'
          }, { rootSessionId: 'root', depth: 1 })
        ],
        getTerminalReplay: async (sessionId: string) => `replay:${sessionId}`
      }))
      const res = await get(port, '/ctl/session/child/wait?timeoutMs=100', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.result.output.text).toBe('replay:child')
      expect(body.data.result.report.outcome).toBe('completed')
    })

    test('returns wait_timeout as 408', async () => {
      const { port } = await startServer(makeDeps({
        waitForSessionStateChange: async () => 'timeout'
      }))
      const res = await get(port, '/ctl/session/root/wait?timeoutMs=1', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(408)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('wait_timeout')
    })

    test('returns invalid_request for invalid timeoutMs', async () => {
      const { port } = await startServer(makeDeps({
        waitForSessionStateChange: async () => 'timeout'
      }))
      const res = await get(port, '/ctl/session/root/wait?timeoutMs=1.5', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(400)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('invalid_request')
    })

    test('returns unknown_session for missing wait target', async () => {
      const { port } = await startServer(makeDeps())
      const res = await get(port, '/ctl/session/missing/wait?timeoutMs=1', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(404)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('unknown_session')
    })
  })

  describe('/ctl/session/:id/prompt', () => {
    test('dispatches prompt to session', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/root/prompt', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({ text: 'hello' }))
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.kind).toBe('dispatched')
    })

    test('returns forbidden_authority_scope when session caller lacks authority', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'child'],
          isVisible: () => true,
          checkAuthority: (_v: string, _t: string, action: string) =>
            action === 'prompt' ? { allowed: false, reason: 'forbidden_authority_scope' } : { allowed: true }
        } as any
      })
      const { port } = await startServer(deps)
      const res = await post(port, '/ctl/session/child/prompt', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' }, JSON.stringify({ text: 'hi' }))
      expect(res.statusCode).toBe(403)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('forbidden_authority_scope')
    })

    test('returns unknown_session for invisible target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const { port } = await startServer(deps)
      const res = await post(port, '/ctl/session/child/prompt', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' }, JSON.stringify({ text: 'hi' }))
      expect(res.statusCode).toBe(404)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('unknown_session')
    })
  })

  describe('/ctl/session/:id/destroy', () => {
    test('destroys session for local-user', async () => {
      let destroyed = false
      const deps = makeDeps({ destroySession: async () => { destroyed = true } })
      const { port } = await startServer(deps)
      const res = await post(port, '/ctl/session/child/destroy', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(200)
      expect(destroyed).toBe(true)
    })

    test('returns forbidden_authority_scope for peer session caller', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'child'],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      })
      const { port } = await startServer(deps)
      const res = await post(port, '/ctl/session/child/destroy', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' })
      expect(res.statusCode).toBe(403)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('forbidden_authority_scope')
    })
  })

  describe('/ctl/session/create', () => {
    test('creates a root session for local-user when projectId is provided without parentId', async () => {
      let requestBody: unknown = null
      const { port } = await startServer(makeDeps({
        createChildSession: async (request) => {
          requestBody = request
          return makeSession({ id: 'new-root' })
        }
      }))
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        projectId: 'proj-1',
        type: 'codex',
        title: 'new root'
      }))
      expect(res.statusCode).toBe(200)
      expect(requestBody).toEqual({
        parentId: '',
        projectId: 'proj-1',
        type: 'codex',
        title: 'new root'
      })
      const body = JSON.parse(res.body)
      expect(body.data.session.id).toBe('new-root')
    })

    test('creates a direct child session for session caller without explicit projectId or parentId', async () => {
      let requestBody: unknown = null
      const { port } = await startServer(makeDeps({
        createChildSession: async (request) => {
          requestBody = request
          return makeSession({ id: 'new-child', parentSessionId: 'root', createdBySessionId: 'root' })
        }
      }))
      const res = await post(port, '/ctl/session/create', { 'x-stoa-session-id': 'root', 'x-stoa-session-token': 'tok_root_1234' }, JSON.stringify({
        type: 'codex',
        title: 'new child'
      }))
      expect(res.statusCode).toBe(200)
      expect(requestBody).toEqual({
        parentId: 'root',
        projectId: '',
        type: 'codex',
        title: 'new child'
      })
      const body = JSON.parse(res.body)
      expect(body.data.session.id).toBe('new-child')
    })

    test('continues to authorize a session caller that was added after server startup', async () => {
      const nodes = [
        makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 })
      ]
      let requestBody: unknown = null
      const { port } = await startServer({
        getSnapshot: () => nodes,
        visibilityService: new SessionVisibilityService(nodes),
        sessionInput: { send: async () => {} },
        createChildSession: async (request) => {
          requestBody = request
          return makeSession({
            id: 'grandchild',
            parentSessionId: 'child',
            createdBySessionId: 'child'
          })
        },
        destroySession: async () => {},
        getTerminalReplay: async () => '',
        ctlSecret: 'test-secret-1234',
        sessionTokenRegistry: new Map([
          ['root', 'tok_root_1234'],
          ['child', 'tok_child_5678']
        ])
      })

      nodes.push(
        makeNode(
          { id: 'child', parentSessionId: 'root', createdBySessionId: 'root' },
          { rootSessionId: 'root', depth: 1 }
        )
      )

      const res = await post(
        port,
        '/ctl/session/create',
        { 'x-stoa-session-id': 'child', 'x-stoa-session-token': 'tok_child_5678' },
        JSON.stringify({
          type: 'codex',
          title: 'grandchild'
        })
      )

      expect(res.statusCode).toBe(200)
      expect(requestBody).toEqual({
        parentId: 'child',
        projectId: '',
        type: 'codex',
        title: 'grandchild'
      })
      const body = JSON.parse(res.body)
      expect(body.data.session.id).toBe('grandchild')
    })

    test('creates a child session when parentId and projectId are provided', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        parentId: 'root',
        projectId: 'proj-1',
        type: 'codex',
        title: 'new child'
      }))
      expect(res.statusCode).toBe(200)
      const body = JSON.parse(res.body)
      expect(body.data.session).toBeDefined()
    })

    test('returns 400 for missing projectId in local-user child create', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        parentId: 'root',
        type: 'codex',
        title: 'child'
      }))
      expect(res.statusCode).toBe(400)
    })

    test('treats missing parentId plus projectId as local-user root create', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        projectId: 'proj-1',
        type: 'codex',
        title: 'orphan'
      }))
      expect(res.statusCode).toBe(200)
    })

    test('returns 400 for missing type', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        parentId: 'root',
        projectId: 'proj-1',
        title: 'child'
      }))
      expect(res.statusCode).toBe(400)
    })

    test('returns 400 for invalid initial dimensions', async () => {
      let called = false
      const { port } = await startServer(makeDeps({
        createChildSession: async () => {
          called = true
          return makeSession({ id: 'new-child' })
        }
      }))
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        parentId: 'root',
        projectId: 'proj-1',
        type: 'codex',
        title: 'child',
        initialCols: 0,
        initialRows: 24
      }))
      expect(res.statusCode).toBe(400)
      expect(called).toBe(false)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('invalid_request')
    })

    test('returns 400 for whitespace-only type', async () => {
      const { port } = await startServer(makeDeps())
      const res = await post(port, '/ctl/session/create', { 'x-stoa-secret': 'test-secret-1234' }, JSON.stringify({
        parentId: 'root',
        projectId: 'proj-1',
        type: '   ',
        title: 'child'
      }))
      expect(res.statusCode).toBe(400)
    })
  })

  describe('stoa-ctl disabled gate', () => {
    test('/ctl/health returns 503 disabled envelope when isCtlEnabled is false', async () => {
      const { port } = await startServer(makeDeps({ isCtlEnabled: () => false }))
      const res = await get(port, '/ctl/health', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(503)
      const body = JSON.parse(res.body)
      expect(body.ok).toBe(false)
      expect(body.error.code).toBe('disabled')
      expect(body.error.message).toBe('stoa-ctl is disabled in settings')
    })

    test('/ctl/health returns 503 disabled envelope even without credentials when gate is off', async () => {
      const { port } = await startServer(makeDeps({ isCtlEnabled: () => false }))
      const res = await get(port, '/ctl/health')
      expect(res.statusCode).toBe(503)
      const body = JSON.parse(res.body)
      expect(body.ok).toBe(false)
      expect(body.error.code).toBe('disabled')
    })

    test('/ctl/session/list returns 503 disabled envelope when isCtlEnabled is false', async () => {
      const { port } = await startServer(makeDeps({ isCtlEnabled: () => false }))
      const res = await get(port, '/ctl/session/list', { 'x-stoa-secret': 'test-secret-1234' })
      expect(res.statusCode).toBe(503)
      const body = JSON.parse(res.body)
      expect(body.error.code).toBe('disabled')
    })
  })
})
