import { describe, expect, test } from 'vitest'
import type { SessionNodeSnapshot, SessionSummary } from '@shared/project-session'
import type { AuthorityResult } from './session-visibility-service'
import { SessionSupervisor, type CallerIdentity, type SessionSupervisorDeps } from './session-supervisor'

function makeSession(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 'root',
    projectId: 'proj-1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'claude-code',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'root',
    summary: '',
    titleGenerationContext: { prompt: null, assistantSnippet: null, contextUpdatedAt: null, autoGeneratedTurnEpoch: null },
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: '2026-05-29T00:00:00.000Z',
    updatedAt: '2026-05-29T00:00:00.000Z',
    lastActivatedAt: null,
    archived: false,
    ...overrides
  }
}

function makeNode(overrides: Partial<SessionSummary> = {}, treeOverrides: Record<string, unknown> = {}): SessionNodeSnapshot {
  const session = makeSession(overrides)
  return {
    session,
    tree: {
      rootSessionId: 'root',
      depth: 0,
      childCount: 0,
      descendantCount: 0,
      ...treeOverrides
    }
  }
}

function localUser(): CallerIdentity {
  return { type: 'local-user' }
}

function sessionCaller(sessionId: string): CallerIdentity {
  return { type: 'session', sessionId }
}

describe('SessionSupervisor', () => {
  function makeDeps(overrides: Partial<SessionSupervisorDeps> = {}): SessionSupervisorDeps {
    const root = makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 })
    const child = makeNode(
      { id: 'child', parentSessionId: 'root', createdBySessionId: 'root' },
      { rootSessionId: 'root', depth: 1 }
    )
    const grandchild = makeNode(
      { id: 'grandchild', parentSessionId: 'child', createdBySessionId: 'child' },
      { rootSessionId: 'root', depth: 2 }
    )
    const peer = makeNode({ id: 'peer' }, { rootSessionId: 'root', depth: 0 })
    const nodes = [root, child, grandchild, peer]

    return {
      getSnapshot: () => nodes,
      visibilityService: {
        visibleSessionIds: () => nodes.map((n) => n.session.id),
        isVisible: () => true,
        checkAuthority: (_viewerId: string, _targetId: string, _action: string): AuthorityResult => ({ allowed: true })
      } as any,
      sessionInput: {
        send: async () => {}
      },
      createChildSession: overrides.createChildSession ?? (async () => makeSession({ id: 'new-child' })),
      destroySession: overrides.destroySession ?? (async () => {}),
      ...overrides
    }
  }

  describe('listSessions', () => {
    test('returns all snapshot nodes for local-user caller', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const result = supervisor.listSessions(localUser())
      expect(result).toHaveLength(4)
      expect(result.map((n) => n.session.id)).toContain('root')
    })

    test('returns only visible sessions for session caller', () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: (viewerId: string) => viewerId === 'root' ? ['root', 'child', 'grandchild'] : [],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: true })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      const result = supervisor.listSessions(sessionCaller('root'))
      expect(result).toHaveLength(3)
    })
  })

  describe('inspectSession', () => {
    test('returns node snapshot for existing session', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const node = supervisor.inspectSession(localUser(), 'root')
      expect(node).toBeDefined()
      expect(node!.session.id).toBe('root')
    })

    test('returns null for non-existent session', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const node = supervisor.inspectSession(localUser(), 'nonexistent')
      expect(node).toBeNull()
    })

    test('returns null for session caller when target is not visible', () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      const node = supervisor.inspectSession(sessionCaller('root'), 'peer')
      expect(node).toBeNull()
    })
  })

  describe('promptSession', () => {
    test('sends prompt text to session via sessionInput', async () => {
      const sent: Array<{ sessionId: string; data: string }> = []
      const deps = makeDeps({
        sessionInput: {
          send: async (sessionId: string, data: string) => { sent.push({ sessionId, data }) }
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const result = await supervisor.promptSession(localUser(), 'root', 'hello')
      expect(result.kind).toBe('dispatched')
      expect(sent).toHaveLength(1)
      expect(sent[0]).toEqual({ sessionId: 'root', data: 'hello\r' })
    })

    test('rejects local-user prompt for non-existent target with unknown_session', async () => {
      const sent: Array<{ sessionId: string; data: string }> = []
      const deps = makeDeps({
        sessionInput: {
          send: async (sessionId: string, data: string) => { sent.push({ sessionId, data }) }
        }
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.promptSession(localUser(), 'missing', 'hello'))
        .rejects.toThrow('unknown_session')
      expect(sent).toHaveLength(0)
    })

    test('throws unknown_session for invisible target from session caller', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.promptSession(sessionCaller('root'), 'peer', 'hi'))
        .rejects.toThrow('unknown_session')
    })

    test('throws forbidden_authority_scope for visible but unauthorized target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: (_v: string, _t: string, action: string) =>
            action === 'prompt' ? { allowed: false, reason: 'forbidden_authority_scope' } : { allowed: true }
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.promptSession(sessionCaller('root'), 'peer', 'hi'))
        .rejects.toThrow('forbidden_authority_scope')
    })
  })

  describe('createChildSession', () => {
    test('allows local-user root create without a parentId', async () => {
      let captured: unknown = null
      const deps = makeDeps({
        createChildSession: async (request) => {
          captured = request
          return makeSession({ id: 'new-root' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(localUser(), { parentId: '', projectId: 'proj-1', type: 'codex', title: 'root' })
      expect(session.id).toBe('new-root')
      expect(captured).toEqual({ parentId: '', projectId: 'proj-1', type: 'codex', title: 'root' })
    })

    test('rewrites session caller create to a direct child of self', async () => {
      let captured: unknown = null
      const deps = makeDeps({
        createChildSession: async (request) => {
          captured = request
          return makeSession({ id: 'new-child', parentSessionId: 'root', createdBySessionId: 'root' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(sessionCaller('root'), { parentId: '', projectId: '', type: 'codex', title: 'child' })
      expect(session.id).toBe('new-child')
      expect(captured).toEqual({ parentId: 'root', projectId: '', type: 'codex', title: 'child' })
    })

    test('delegates to deps.createChildSession for local-user', async () => {
      let called = false
      const deps = makeDeps({
        createChildSession: async () => { called = true; return makeSession({ id: 'new-child' }) }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(localUser(), { parentId: 'root', projectId: 'proj-1', type: 'codex', title: 'child' })
      expect(called).toBe(true)
      expect(session.id).toBe('new-child')
    })

    test('rejects when session caller in tree has no create authority on target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: (_v: string, _t: string, action: string) =>
            action === 'create' ? { allowed: false, reason: 'forbidden_authority_scope' } : { allowed: true }
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.createChildSession(sessionCaller('root'), { parentId: 'peer', projectId: 'proj-1', type: 'codex', title: 'child' }))
        .rejects.toThrow('forbidden_authority_scope')
    })

    test('rejects session caller not in tree with unknown_session', async () => {
      let called = false
      const deps = makeDeps({
        getSnapshot: () => [],
        createChildSession: async () => {
          called = true
          return makeSession({ id: 'new-child', parentSessionId: 'outsider', createdBySessionId: 'outsider' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(
        supervisor.createChildSession(sessionCaller('outsider'), { parentId: '', projectId: '', type: 'shell', title: 'child' })
      ).rejects.toThrow('unknown_session')
      expect(called).toBe(false)
    })
  })

  describe('destroySession', () => {
    test('delegates to deps.destroySession for local-user', async () => {
      let called = false
      const deps = makeDeps({
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)
      await supervisor.destroySession(localUser(), 'child')
      expect(called).toBe(true)
    })

    test('rejects local-user destroy for non-existent target with unknown_session', async () => {
      let called = false
      const deps = makeDeps({
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.destroySession(localUser(), 'missing'))
        .rejects.toThrow('unknown_session')
      expect(called).toBe(false)
    })

    test('rejects destroy of same-depth peer for session caller', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.destroySession(sessionCaller('root'), 'peer'))
        .rejects.toThrow('forbidden_authority_scope')
    })

    test('allows destroy of descendant for session caller', async () => {
      let called = false
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'child', 'grandchild'],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: true })
        } as any,
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)
      await supervisor.destroySession(sessionCaller('root'), 'grandchild')
      expect(called).toBe(true)
    })
  })
})
