import { describe, expect, test, vi } from 'vitest'
import type { SessionNodeSnapshot, SessionSummary } from '@shared/project-session'
import type { AuthorityResult } from './session-visibility-service'
import { SessionSupervisor, type CallerIdentity, type SessionSupervisorDeps } from './session-supervisor'

function makeSession(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 'root',
    projectId: 'proj-1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'claude-code',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'root',
    summary: '',
    titleGenerationContext: { prompt: null, assistantSnippet: null, contextUpdatedAt: null, autoGeneratedTurnEpoch: null },
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: '2026-05-29T00:00:00.000Z',
    updatedAt: '2026-05-29T00:00:00.000Z',
    lastActivatedAt: null,
    archived: false,
    ...overrides
  }
}

function makeNode(overrides: Partial<SessionSummary> = {}, treeOverrides: Record<string, unknown> = {}): SessionNodeSnapshot {
  const session = makeSession(overrides)
  return {
    session,
    tree: {
      rootSessionId: 'root',
      depth: 0,
      childCount: 0,
      descendantCount: 0,
      ...treeOverrides
    }
  }
}

function localUser(): CallerIdentity {
  return { type: 'local-user' }
}

function sessionCaller(sessionId: string): CallerIdentity {
  return { type: 'session', sessionId }
}

describe('SessionSupervisor', () => {
  function makeDeps(overrides: Partial<SessionSupervisorDeps> = {}): SessionSupervisorDeps {
    const root = makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 })
    const child = makeNode(
      { id: 'child', parentSessionId: 'root', createdBySessionId: 'root' },
      { rootSessionId: 'root', depth: 1 }
    )
    const grandchild = makeNode(
      { id: 'grandchild', parentSessionId: 'child', createdBySessionId: 'child' },
      { rootSessionId: 'root', depth: 2 }
    )
    const peer = makeNode({ id: 'peer' }, { rootSessionId: 'root', depth: 0 })
    const nodes = [root, child, grandchild, peer]

    return {
      getSnapshot: () => nodes,
      visibilityService: {
        visibleSessionIds: () => nodes.map((n) => n.session.id),
        isVisible: () => true,
        checkAuthority: (_viewerId: string, _targetId: string, _action: string): AuthorityResult => ({ allowed: true })
      } as any,
      sessionInput: {
        send: async () => {}
      },
      createChildSession: overrides.createChildSession ?? (async () => makeSession({ id: 'new-child' })),
      destroySession: overrides.destroySession ?? (async () => {}),
      getTerminalReplay: overrides.getTerminalReplay ?? (async () => ''),
      ...overrides
    }
  }

  describe('listSessions', () => {
    test('returns all snapshot nodes for local-user caller', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const result = supervisor.listSessions(localUser())
      expect(result).toHaveLength(4)
      expect(result.map((n) => n.session.id)).toContain('root')
    })

    test('returns only visible sessions for session caller', () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: (viewerId: string) => viewerId === 'root' ? ['root', 'child', 'grandchild'] : [],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: true })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      const result = supervisor.listSessions(sessionCaller('root'))
      expect(result).toHaveLength(3)
    })

    test('sanitizes subagent full result body from generic list projection', () => {
      const supervisor = new SessionSupervisor(makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            subagentResultSummary: {
              status: 'completed',
              title: 'done',
              createdAt: '2026-06-11T00:00:00.000Z',
              updatedAt: '2026-06-11T00:00:01.000Z',
              hasBody: true
            },
            subagentResult: {
              sessionId: 'child',
              parentSessionId: 'root',
              inputEpoch: 1,
              status: 'completed',
              title: 'done',
              body: 'secret body',
              createdAt: '2026-06-11T00:00:00.000Z',
              updatedAt: '2026-06-11T00:00:01.000Z'
            }
          }, { rootSessionId: 'root', depth: 1 })
        ]
      }))

      const result = supervisor.listSessions(localUser())
      expect(result[1]?.session.subagentResultSummary?.hasBody).toBe(true)
      expect(result[1]?.session.subagentResult).toBeUndefined()
    })
  })

  describe('inspectSession', () => {
    test('returns node snapshot for existing session', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const node = supervisor.inspectSession(localUser(), 'root')
      expect(node).toBeDefined()
      expect(node!.session.id).toBe('root')
    })

    test('returns null for non-existent session', () => {
      const supervisor = new SessionSupervisor(makeDeps())
      const node = supervisor.inspectSession(localUser(), 'nonexistent')
      expect(node).toBeNull()
    })

    test('returns null for session caller when target is not visible', () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      const node = supervisor.inspectSession(sessionCaller('root'), 'peer')
      expect(node).toBeNull()
    })

    test('sanitizes subagent full result body from generic inspect projection', () => {
      const supervisor = new SessionSupervisor(makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            subagentResultSummary: {
              status: 'completed',
              title: 'done',
              createdAt: '2026-06-11T00:00:00.000Z',
              updatedAt: '2026-06-11T00:00:01.000Z',
              hasBody: true
            },
            subagentResult: {
              sessionId: 'child',
              parentSessionId: 'root',
              inputEpoch: 1,
              status: 'completed',
              title: 'done',
              body: 'secret body',
              createdAt: '2026-06-11T00:00:00.000Z',
              updatedAt: '2026-06-11T00:00:01.000Z'
            }
          }, { rootSessionId: 'root', depth: 1 })
        ]
      }))

      const node = supervisor.inspectSession(localUser(), 'child')
      expect(node?.session.subagentResultSummary?.hasBody).toBe(true)
      expect(node?.session.subagentResult).toBeUndefined()
    })
  })

  describe('inputSession', () => {
    test('sends input text to session via sessionInput', async () => {
      const sent: Array<{ sessionId: string; data: string }> = []
      const deps = makeDeps({
        sessionInput: {
          send: async (sessionId: string, data: string) => { sent.push({ sessionId, data }) }
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const result = await supervisor.inputSession(localUser(), 'root', 'hello')
      expect(result.kind).toBe('dispatched')
      expect(sent).toHaveLength(1)
      expect(sent[0]).toEqual({ sessionId: 'root', data: 'hello\r' })
    })

    test('rejects local-user input for non-existent target with unknown_session', async () => {
      const sent: Array<{ sessionId: string; data: string }> = []
      const deps = makeDeps({
        sessionInput: {
          send: async (sessionId: string, data: string) => { sent.push({ sessionId, data }) }
        }
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.inputSession(localUser(), 'missing', 'hello'))
        .rejects.toThrow('unknown_session')
      expect(sent).toHaveLength(0)
    })

    test('throws unknown_session for invisible target from session caller', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => [],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'unknown_session' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.inputSession(sessionCaller('root'), 'peer', 'hi'))
        .rejects.toThrow('unknown_session')
    })

    test('throws forbidden_authority_scope for visible but unauthorized target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: (_v: string, _t: string, action: string) =>
            action === 'input' ? { allowed: false, reason: 'forbidden_authority_scope' } : { allowed: true }
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.inputSession(sessionCaller('root'), 'peer', 'hi'))
        .rejects.toThrow('forbidden_authority_scope')
    })

    test('records subagent input invalidation when target is a child session', async () => {
      const recordSubagentInput = vi.fn(async () => null)
      const supervisor = new SessionSupervisor({
        ...makeDeps(),
        recordSubagentInput
      })

      await supervisor.inputSession(localUser(), 'child', 'hello')

      expect(recordSubagentInput).toHaveBeenCalledWith('child', 'hello')
    })
  })

  describe('createChildSession', () => {
    test('allows local-user root create without a parentId', async () => {
      let captured: unknown = null
      const deps = makeDeps({
        createChildSession: async (request) => {
          captured = request
          return makeSession({ id: 'new-root' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(localUser(), { parentId: '', projectId: 'proj-1', type: 'codex', title: 'root' })
      expect(session.id).toBe('new-root')
      expect(captured).toEqual({ parentId: '', projectId: 'proj-1', type: 'codex', title: 'root' })
    })

    test('rewrites session caller create to a direct child of self', async () => {
      let captured: unknown = null
      const deps = makeDeps({
        createChildSession: async (request) => {
          captured = request
          return makeSession({ id: 'new-child', parentSessionId: 'root', createdBySessionId: 'root' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(sessionCaller('root'), { parentId: '', projectId: '', type: 'codex', title: 'child' })
      expect(session.id).toBe('new-child')
      expect(captured).toEqual({ parentId: 'root', projectId: '', type: 'codex', title: 'child' })
    })

    test('delegates to deps.createChildSession for local-user', async () => {
      let called = false
      const deps = makeDeps({
        createChildSession: async () => { called = true; return makeSession({ id: 'new-child' }) }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(localUser(), { parentId: 'root', projectId: 'proj-1', type: 'codex', title: 'child' })
      expect(called).toBe(true)
      expect(session.id).toBe('new-child')
    })

    test('preserves initialized subagent facade fields from child session creation', async () => {
      const deps = makeDeps({
        createChildSession: async (request) => {
          expect(request.parentId).toBe('root')
          return makeSession({
            id: 'new-child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            subagentName: 'ryu',
            subagentInputEpoch: 0,
            subagentResultSummary: null,
            subagentResult: null
          })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      const session = await supervisor.createChildSession(sessionCaller('root'), { parentId: '', projectId: '', type: 'codex', title: 'child' })
      expect(session).toMatchObject({
        id: 'new-child',
        subagentName: 'ryu',
        subagentInputEpoch: 0,
        subagentResultSummary: null,
        subagentResult: null
      })
    })

    test('rejects when session caller in tree has no create authority on target', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: (_v: string, _t: string, action: string) =>
            action === 'create' ? { allowed: false, reason: 'forbidden_authority_scope' } : { allowed: true }
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.createChildSession(sessionCaller('root'), { parentId: 'peer', projectId: 'proj-1', type: 'codex', title: 'child' }))
        .rejects.toThrow('forbidden_authority_scope')
    })

    test('rejects session caller not in tree with unknown_session', async () => {
      let called = false
      const deps = makeDeps({
        getSnapshot: () => [],
        createChildSession: async () => {
          called = true
          return makeSession({ id: 'new-child', parentSessionId: 'outsider', createdBySessionId: 'outsider' })
        }
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(
        supervisor.createChildSession(sessionCaller('outsider'), { parentId: '', projectId: '', type: 'shell', title: 'child' })
      ).rejects.toThrow('unknown_session')
      expect(called).toBe(false)
    })
  })

  describe('destroySession', () => {
    test('delegates to deps.destroySession for local-user', async () => {
      let called = false
      const deps = makeDeps({
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)
      await supervisor.destroySession(localUser(), 'child')
      expect(called).toBe(true)
    })

    test('rejects local-user destroy for non-existent target with unknown_session', async () => {
      let called = false
      const deps = makeDeps({
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.destroySession(localUser(), 'missing'))
        .rejects.toThrow('unknown_session')
      expect(called).toBe(false)
    })

    test('rejects destroy of same-depth peer for session caller', async () => {
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'peer'],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      })
      const supervisor = new SessionSupervisor(deps)
      await expect(supervisor.destroySession(sessionCaller('root'), 'peer'))
        .rejects.toThrow('forbidden_authority_scope')
    })

    test('allows destroy of descendant for session caller', async () => {
      let called = false
      const deps = makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root', 'child', 'grandchild'],
          isVisible: () => true,
          checkAuthority: () => ({ allowed: true })
        } as any,
        destroySession: async () => { called = true }
      })
      const supervisor = new SessionSupervisor(deps)
      await supervisor.destroySession(sessionCaller('root'), 'grandchild')
      expect(called).toBe(true)
    })
  })

  describe('subsession observation controls', () => {
    test('getSessionStatus rejects unknown and forbidden targets', () => {
      const unknownSupervisor = new SessionSupervisor(makeDeps())
      try {
        unknownSupervisor.getSessionStatus(localUser(), 'missing')
        throw new Error('expected unknown_session')
      } catch (error: any) {
        expect(error.code).toBe('unknown_session')
      }

      const forbiddenSupervisor = new SessionSupervisor(makeDeps({
        visibilityService: {
          visibleSessionIds: () => ['root'],
          isVisible: () => false,
          checkAuthority: () => ({ allowed: false, reason: 'forbidden_authority_scope' })
        } as any
      }))
      try {
        forbiddenSupervisor.getSessionStatus(sessionCaller('root'), 'child')
        throw new Error('expected forbidden_authority_scope')
      } catch (error: any) {
        expect(error.code).toBe('forbidden_authority_scope')
      }
    })

    test('waitForSession returns completed session output and report when target is already terminal', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 2,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: true,
            summary: 'child completed'
          }, { rootSessionId: 'root', depth: 1 })
        ],
        getTerminalReplay: async () => 'child output'
      })
      const supervisor = new SessionSupervisor(deps)

      const result = await supervisor.waitForSession(sessionCaller('root'), 'child', { timeoutMs: 1000 })

      expect(result.session.session.id).toBe('child')
      expect(result.output.text).toBe('child output')
      expect(result.report?.outcome).toBe('completed')
      expect(result.report?.summary).toBe('child completed')
    })

    test('waitForSession waits until a non-terminal session reaches completion', async () => {
      let child = makeNode({
        id: 'child',
        parentSessionId: 'root',
        createdBySessionId: 'root',
        turnEpoch: 1,
        lastTurnOutcome: 'none',
        hasUnseenCompletion: false
      }, { rootSessionId: 'root', depth: 1 })
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          child
        ],
        getTerminalReplay: async () => 'done output',
        waitForSessionStateChange: async () => {
          child = makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 2,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: false,
            summary: 'done'
          }, { rootSessionId: 'root', depth: 1 })
          return 'updated'
        }
      })
      const supervisor = new SessionSupervisor(deps)

      const result = await supervisor.waitForSession(sessionCaller('root'), 'child', { timeoutMs: 1000 })

      expect(result.output.text).toBe('done output')
      expect(result.report).toMatchObject({
        sessionId: 'child',
        outcome: 'completed',
        hasUnseenCompletion: false,
        summary: 'done'
      })
      expect(result.status.hasCompletionReport).toBe(true)
    })

    test('waitForSession uses bounded waiter intervals so missed notifications do not wait for the full timeout', async () => {
      let observedTimeoutMs = 0
      let child = makeNode({
        id: 'child',
        parentSessionId: 'root',
        createdBySessionId: 'root',
        turnEpoch: 1,
        lastTurnOutcome: 'none'
      }, { rootSessionId: 'root', depth: 1 })
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          child
        ],
        waitForSessionStateChange: async (_sessionId, timeoutMs) => {
          observedTimeoutMs = timeoutMs
          child = makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 2,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: false
          }, { rootSessionId: 'root', depth: 1 })
          return 'timeout'
        }
      })
      const supervisor = new SessionSupervisor(deps)

      const result = await supervisor.waitForSession(sessionCaller('root'), 'child', { timeoutMs: 10_000 })

      expect(observedTimeoutMs).toBeLessThanOrEqual(250)
      expect(result.report?.outcome).toBe('completed')
    })

    test('waitForSession rejects with wait_timeout when target does not reach a terminal state', async () => {
      const deps = makeDeps({
        getTerminalReplay: async () => '',
        waitForSessionStateChange: async () => 'timeout'
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.waitForSession(localUser(), 'root', { timeoutMs: 1 }))
        .rejects.toMatchObject({ code: 'wait_timeout' })
    })

    test('getSessionOutput returns terminal replay for visible sessions', async () => {
      const deps = makeDeps({
        getTerminalReplay: async (sessionId: string) => `replay:${sessionId}`
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.getSessionOutput(sessionCaller('root'), 'child'))
        .resolves.toEqual({ sessionId: 'child', text: 'replay:child' })
    })

    test('getSessionOutput rejects same-depth peer subagent reads without full-body authority', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({ id: 'a', parentSessionId: 'root', createdBySessionId: 'root' }, { rootSessionId: 'root', depth: 1 }),
          makeNode({
            id: 'b',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            lastTurnOutcome: 'completed'
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.getSessionOutput(sessionCaller('a'), 'b'))
        .rejects.toMatchObject({ code: 'forbidden_authority_scope' })
    })

    test('getSessionOutput rejects stale subagent terminal fallback after a newer input epoch', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            lastTurnOutcome: 'completed',
            subagentInputEpoch: 1,
            subagentLatestInputStateSequence: 7,
            lastStateSequence: 7
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.getSessionOutput(localUser(), 'child'))
        .rejects.toMatchObject({ code: 'no_completion_yet' })
    })

    test('getSessionOutput rejects destroyed subagent terminal fallback', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            lastTurnOutcome: 'completed',
            archived: true
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.getSessionOutput(localUser(), 'child'))
        .rejects.toMatchObject({ code: 'no_completion_yet' })
    })

    test('getCompletionReport rejects with no_completion_yet for non-terminal sessions', async () => {
      const supervisor = new SessionSupervisor(makeDeps())

      await expect(supervisor.getCompletionReport(localUser(), 'root'))
        .rejects.toMatchObject({ code: 'no_completion_yet' })
    })

    test('getCompletionReport returns completed reports even after completion has been seen', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({
            id: 'seen-complete',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 7,
            lastTurnOutcome: 'completed',
            hasUnseenCompletion: false,
            summary: 'already read'
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      const report = await supervisor.getCompletionReport(localUser(), 'seen-complete')

      expect(report).toMatchObject({
        sessionId: 'seen-complete',
        outcome: 'completed',
        hasUnseenCompletion: false,
        summary: 'already read'
      })
      expect(supervisor.getSessionStatus(localUser(), 'seen-complete').hasCompletionReport).toBe(true)
    })

    test('getCompletionReport returns report for failed sessions', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({
            id: 'failed-child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 3,
            lastTurnOutcome: 'failed',
            failureReason: 'tool_error',
            summary: 'tool failed'
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      const report = await supervisor.getCompletionReport(localUser(), 'failed-child')

      expect(report).toMatchObject({
        sessionId: 'failed-child',
        outcome: 'failed',
        failureReason: 'tool_error',
        summary: 'tool failed'
      })
    })

    test('getCompletionReport rejects stale subagent terminal fallback after a newer input epoch', async () => {
      const deps = makeDeps({
        getSnapshot: () => [
          makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
          makeNode({
            id: 'child',
            parentSessionId: 'root',
            createdBySessionId: 'root',
            turnEpoch: 2,
            lastTurnOutcome: 'completed',
            subagentInputEpoch: 1,
            subagentLatestInputStateSequence: 9,
            lastStateSequence: 9
          }, { rootSessionId: 'root', depth: 1 })
        ]
      })
      const supervisor = new SessionSupervisor(deps)

      await expect(supervisor.getCompletionReport(localUser(), 'child'))
        .rejects.toMatchObject({ code: 'no_completion_yet' })
    })
  })
})
