import { describe, expect, test } from 'vitest'
import { SessionVisibilityService } from './session-visibility-service'
import type { SessionSummary, SessionTreeMeta, SessionNodeSnapshot } from '@shared/project-session'

function node(
  id: string,
  parentId: string | null,
  depth: number,
  overrides?: Partial<SessionSummary>,
  treeOverrides?: Partial<SessionTreeMeta>
): SessionNodeSnapshot {
  const now = '2026-05-29T00:00:00.000Z'
  return {
    session: {
      id,
      projectId: 'project-1',
      parentSessionId: parentId,
      createdBySessionId: parentId,
      type: 'claude-code',
      runtimeState: 'alive',
      turnState: 'idle',
      turnEpoch: 0,
      lastTurnOutcome: 'none',
      blockingReason: null,
      failureReason: null,
      hasUnseenCompletion: false,
      runtimeExitCode: null,
      runtimeExitReason: null,
      lastStateSequence: 0,
      title: id,
      summary: '',
      titleGenerationContext: { prompt: null, assistantSnippet: null, contextUpdatedAt: null, autoGeneratedTurnEpoch: null },
      recoveryMode: 'fresh-shell',
      externalSessionId: null,
      createdAt: now,
      updatedAt: now,
      lastActivatedAt: null,
      archived: false,
      ...overrides
    },
    tree: {
      rootSessionId: id,
      depth,
      childCount: 0,
      descendantCount: 0,
      ...treeOverrides
    }
  }
}

describe('SessionVisibilityService', () => {
  describe('visibleSessionIds', () => {
    test('returns self for a single root session', () => {
      const nodes = [node('root', null, 0)]
      const service = new SessionVisibilityService(nodes)
      expect(service.visibleSessionIds('root')).toEqual(['root'])
    })

    test('returns same-depth peers and descendants for a mid-tree session', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
        node('A2', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const visible = service.visibleSessionIds('A')
      expect(visible).toEqual(expect.arrayContaining(['A', 'B', 'A1', 'A2']))
      expect(visible).toHaveLength(4)
    })

    test('root sees all sessions at depth 0 plus their descendants', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.visibleSessionIds('root')).toEqual(expect.arrayContaining(['root', 'A', 'A1']))
    })

    test('leaf session sees its same-depth siblings but not parent', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
        node('A2', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const visible = service.visibleSessionIds('A1')
      expect(visible).toEqual(expect.arrayContaining(['A1', 'A2']))
      expect(visible).not.toContain('A')
      expect(visible).not.toContain('root')
    })

    test('does not expose same-depth peers from another session tree', () => {
      const nodes = [
        node('root-1', null, 0),
        node('A', 'root-1', 1, undefined, { rootSessionId: 'root-1' }),
        node('root-2', null, 0),
        node('B', 'root-2', 1, undefined, { rootSessionId: 'root-2' })
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.visibleSessionIds('A')).toEqual(['A'])
      expect(service.isVisible('A', 'B')).toBe(false)
      expect(service.visibleSessionIds('root-1')).toEqual(expect.arrayContaining(['root-1', 'A']))
      expect(service.visibleSessionIds('root-1')).not.toContain('root-2')
      expect(service.visibleSessionIds('root-1')).not.toContain('B')
    })

    test('returns empty for unknown session', () => {
      const nodes = [node('root', null, 0)]
      const service = new SessionVisibilityService(nodes)
      expect(service.visibleSessionIds('nonexistent')).toEqual([])
    })
  })

  describe('isVisible', () => {
    test('returns true when target is in the visible set', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.isVisible('A', 'A1')).toBe(true)
      expect(service.isVisible('A', 'A')).toBe(true)
      expect(service.isVisible('A', 'root')).toBe(false)
    })
  })

  describe('checkAuthority', () => {
    test('allows inspect on visible target', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A', 'A1', 'inspect')
      expect(result.allowed).toBe(true)
    })

    test('allows prompt on descendant', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('A', 'A1', 'prompt').allowed).toBe(true)
    })

    test('allows create on self', () => {
      const nodes = [node('root', null, 0)]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('root', 'root', 'create').allowed).toBe(true)
    })

    test('rejects create on descendant because session callers can only create direct children of self', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A', 'A1', 'create')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('forbidden_authority_scope')
    })

    test('allows destroy on self', () => {
      const nodes = [node('root', null, 0)]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('root', 'root', 'destroy').allowed).toBe(true)
    })

    test('allows destroy on descendant', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('A', 'A1', 'destroy').allowed).toBe(true)
    })

    test('rejects destroy on same-depth peer', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A', 'B', 'destroy')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('forbidden_authority_scope')
    })

    test('rejects create on same-depth peer', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A', 'B', 'create')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('forbidden_authority_scope')
    })

    test('allows inspect on same-depth peer', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('A', 'B', 'inspect').allowed).toBe(true)
    })

    test('allows prompt on same-depth peer', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      expect(service.checkAuthority('A', 'B', 'prompt').allowed).toBe(true)
    })

    test('rejects subagentInput on same-depth peer', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('B', 'root', 1, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A', 'B', 'subagentInput')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('forbidden_authority_scope')
    })

    test('rejects ancestor targets as unknown_session because they are outside visibility scope', () => {
      const nodes = [
        node('root', null, 0),
        node('A', 'root', 1, undefined, { rootSessionId: 'root' }),
        node('A1', 'A', 2, undefined, { rootSessionId: 'root' }),
      ]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('A1', 'A', 'destroy')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('unknown_session')
    })
  })

  describe('visibility failure for unknown targets', () => {
    test('returns visibility failure for target not in session tree', () => {
      const nodes = [node('root', null, 0)]
      const service = new SessionVisibilityService(nodes)
      const result = service.checkAuthority('root', 'unknown_session', 'inspect')
      expect(result.allowed).toBe(false)
      expect(result.reason).toBe('unknown_session')
    })
  })
})
