import { describe, expect, test } from 'vitest'
import type { SessionNodeSnapshot, SessionSummary } from '@shared/project-session'
import type { AuthorityResult } from './session-visibility-service'
import { SubagentSupervisor, type SubagentSupervisorDeps } from './subagent-supervisor'
import type { CallerIdentity } from './session-supervisor'

function makeSession(overrides: Partial<SessionSummary> = {}): SessionSummary {
  return {
    id: 'root',
    projectId: 'proj-1',
    parentSessionId: null,
    createdBySessionId: null,
    type: 'claude-code',
    runtimeState: 'alive',
    turnState: 'idle',
    turnEpoch: 0,
    lastTurnOutcome: 'none',
    blockingReason: null,
    failureReason: null,
    hasUnseenCompletion: false,
    runtimeExitCode: null,
    runtimeExitReason: null,
    lastStateSequence: 0,
    title: 'root',
    summary: '',
    titleGenerationContext: { prompt: null, assistantSnippet: null, contextUpdatedAt: null, autoGeneratedTurnEpoch: null },
    recoveryMode: 'fresh-shell',
    externalSessionId: null,
    createdAt: '2026-05-29T00:00:00.000Z',
    updatedAt: '2026-05-29T00:00:00.000Z',
    lastActivatedAt: null,
    archived: false,
    ...overrides
  }
}

function makeNode(overrides: Partial<SessionSummary> = {}, treeOverrides: Record<string, unknown> = {}): SessionNodeSnapshot {
  const session = makeSession(overrides)
  return {
    session,
    tree: {
      rootSessionId: overrides.parentSessionId ? 'root' : session.id,
      depth: overrides.parentSessionId ? 1 : 0,
      childCount: 0,
      descendantCount: 0,
      ...treeOverrides
    }
  }
}

function localUser(): CallerIdentity {
  return { type: 'local-user' }
}

function sessionCaller(sessionId: string): CallerIdentity {
  return { type: 'session', sessionId }
}

describe('SubagentSupervisor', () => {
  function makeDeps(overrides: Partial<SubagentSupervisorDeps> = {}): SubagentSupervisorDeps {
    const root = makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 })
    const child = makeNode(
      { id: 'child', parentSessionId: 'root', createdBySessionId: 'root', subagentName: 'ryu', subagentInputEpoch: 1 },
      { rootSessionId: 'root', depth: 1 }
    )
    const nodes = [root, child]

    return {
      getSnapshot: () => nodes,
      visibilityService: {
        visibleSessionIds: () => nodes.map((n) => n.session.id),
        isVisible: () => true,
        checkAuthority: (_viewerId: string, _targetId: string, _action: string): AuthorityResult => ({ allowed: true })
      } as unknown as SubagentSupervisorDeps['visibilityService'],
      sessionInput: {
        send: async () => {}
      },
      createChildSession: overrides.createChildSession ?? (async () => makeSession({ id: 'new-child', parentSessionId: 'root', createdBySessionId: 'root', subagentName: 'andy', subagentInputEpoch: 0 })),
      destroySession: overrides.destroySession ?? (async () => {}),
      rollbackDispatchedSession: overrides.rollbackDispatchedSession ?? (async () => {}),
      getTerminalReplay: overrides.getTerminalReplay ?? (async () => ''),
      updateSessionFacade: overrides.updateSessionFacade ?? (async (sessionId: string, facade: Record<string, unknown>) => makeSession({ id: sessionId, parentSessionId: 'root', createdBySessionId: 'root', ...facade })),
      interruptSession: overrides.interruptSession ?? (async () => true),
      ...overrides
    }
  }

  test('dispatch returns child alias initialized by generic child creation path', async () => {
    const supervisor = new SubagentSupervisor(makeDeps({
      createChildSession: async () => makeSession({
        id: 'new-child',
        parentSessionId: 'root',
        createdBySessionId: 'root',
        subagentName: 'andy',
        subagentInputEpoch: 0
      })
    }))

    const result = await supervisor.dispatch(sessionCaller('root'), {
      type: 'claude-code',
      text: 'do the thing'
    })

    expect(result.subagent).toMatchObject({
      id: 'new-child',
      name: 'andy'
    })
  })

  test('dispatch rolls back when epoch=1 facade persist fails after input delivery', async () => {
    let inputSent = false
    let rolledBack = false
    let updateCount = 0
    const supervisor = new SubagentSupervisor(makeDeps({
      createChildSession: async () => makeSession({
        id: 'new-child',
        parentSessionId: 'root',
        createdBySessionId: 'root',
        subagentName: 'andy',
        subagentInputEpoch: 0
      }),
      sessionInput: {
        send: async () => { inputSent = true }
      },
      updateSessionFacade: async () => {
        updateCount += 1
        throw new Error('persist failed')
      },
      rollbackDispatchedSession: async () => { rolledBack = true }
    }))

    await expect(
      supervisor.dispatch(sessionCaller('root'), {
        type: 'claude-code',
        text: 'hello'
      })
    ).rejects.toThrow('persist failed')

    expect(inputSent).toBe(true)
    expect(updateCount).toBe(1)
    expect(rolledBack).toBe(true)
  })

  test('list includes child sessions created without explicit dispatch because they are still subagents', () => {
    const nodes = [
      makeNode({ id: 'root' }, { rootSessionId: 'root', depth: 0 }),
      makeNode({ id: 'child-auto', parentSessionId: 'root', createdBySessionId: 'root', subagentName: 'mai', subagentInputEpoch: 0 }, { rootSessionId: 'root', depth: 1 })
    ]
    const supervisor = new SubagentSupervisor(makeDeps({
      getSnapshot: () => nodes
    }))

    const list = supervisor.list(localUser())
    expect(list).toHaveLength(1)
    expect(list[0]).toMatchObject({
      id: 'child-auto',
      name: 'mai'
    })
  })
})
